# Generated by Django 4.2 on 2023-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zippy_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='meta_detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='meta_detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
