# Generated by Django 4.2 on 2023-10-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zippy_form', '0003_formsubmission_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsubmission',
            old_name='entry',
            new_name='revision',
        ),
    ]
