# Generated by Django 4.2 on 2023-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zippy_form', '0006_form_gsheet_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmissiondata',
            name='submission_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
