# Generated by Django 4.2 on 2023-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zippy_form', '0009_alter_webhook_endpoint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='api_accessed_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
