# Generated by Django 4.2 on 2024-02-06 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zippy_form', '0018_remove_formsubmissionpaymentdetails_payment_gateway_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormMetaData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('meta_label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('dropdown', 'Dropdown')], default='text', max_length=255)),
                ('status', models.CharField(choices=[('deleted', 'Deleted'), ('active', 'Active'), ('in_active', 'InActive')], default='active', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zippy_form.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormMetaDataOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('deleted', 'Deleted'), ('active', 'Active'), ('in_active', 'InActive')], default='active', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zippy_form.form')),
                ('form_meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zippy_form.formmetadata')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmissionMetaDataValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_meta_data_type', models.CharField(choices=[('text', 'Text'), ('dropdown', 'Dropdown')], default='text', max_length=255)),
                ('text_field', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dropdown_field', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zippy_form.formmetadataoption')),
                ('form_meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zippy_form.formmetadata')),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zippy_form.formsubmission')),
            ],
        ),
    ]
