# Generated by Django 4.2 on 2024-02-08 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zippy_form', '0019_formmetadata_formmetadataoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormReCaptcha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recaptcha_enabled', models.BooleanField(default=False)),
                ('site_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_recaptcha', to='zippy_form.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormPageViews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zippy_form.form')),
            ],
        ),
    ]
