# Generated by Django 4.2 on 2024-08-01 07:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('zippy_form', '0025_form_gsheet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsettings',
            name='gsheet_type',
            field=models.CharField(choices=[('zippy_form_spreadsheet', 'ZIPPY FORM SPREADSHEET'), ('custom_new_spreadsheet', 'CUSTOM NEW SPREADSHEET'), ('custom_existing_spreadsheet', 'CUSTOM EXISTING SPREADSHEET')], default='zippy_form_spreadsheet', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='FormGsheetMappingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zf_gsheet_url', models.CharField(blank=True, max_length=255)),
                ('custom_gsheet_url', models.CharField(blank=True, max_length=255)),
                ('custom_existing_gsheet_url', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gsheet_mapping_history', to='zippy_form.form')),
            ],
        ),
    ]
