# Generated by Django 4.2 on 2024-08-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zippy_form', '0027_formsettings_sheet_id_formsettings_sub_sheet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsettings',
            name='sheet_id',
        ),
    ]
