# Generated by Django 4.2 on 2024-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zippy_form', '0034_formfielddropdownoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='admin_only',
            new_name='admin_only_edit',
        ),
        migrations.AddField(
            model_name='formfield',
            name='admin_can_submit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='user_can_submit',
            field=models.BooleanField(default=True),
        ),
    ]
