# Generated by Django 4.2 on 2024-12-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zippy_form', '0037_formsubmissiondata_location_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='prefix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formfield',
            name='starts_from',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='formfield',
            name='suffix',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formsubmissiondata',
            name='unique_field',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text_box', 'Text Box'), ('website_url', 'Website URL'), ('text_area', 'TextArea'), ('number', 'Number'), ('email', 'Email'), ('dropdown', 'Dropdown'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('time', 'Time'), ('file', 'File Upload'), ('short_text_area', 'Short TextArea'), ('multiselect_checkbox', 'MultiSelect Checkbox'), ('hidden', 'Hidden'), ('heading', 'Heading'), ('paragraph', 'Paragraph'), ('phone_number', 'Phone Number'), ('dynamic_dropdown', 'Dynamic Dropdown'), ('image', 'Image'), ('signature', 'Signature'), ('location', 'Location'), ('unique_id', 'Unique ID')], max_length=20),
        ),
    ]
