__title__ = "MicroSIP Nextcloud Bridge - Server"
__description__ = "A Bridge between MicroSip and Nextcloud."
__version__ = "0.1.0"
__author__ = "Julius Koenig"
__author_email__ = "info@bastelquartier.de"
__license__ = "GPL-3.0"