from _typeshed import Incomplete
from typing import Any

def verify_token(token: str, app: Incomplete | None = None) -> dict[str, Any]: ...

class _AppCheckService:
    def __init__(self, app) -> None: ...
    def verify_token(self, token: str) -> dict[str, Any]: ...

class _Validators:
    @classmethod
    def check_string(cls, label: str, value: Any): ...
