IMAGE_PROMPT = "Give caption to this image, describe this image thoroughly, do not miss any details"
TABLE_PROMPT = "Reformat the table to a markdown type table. Return me only the markdown type table. Do not add or change any data"
HEADER_PROMPT = "Return me the text. Do not add or change any data. Return only the text in the image"
TITLE_PROMPT = "Return me the text. Do not add or change any data. Return only the text in the image"
FOOTER_PROMPT = "Return me the text. Do not add or change any data. Return only the text in the image"
CHART_PROMPT = "Describe the chart in this image. Describe the trend, metadata, x-axis, and y-axis. Give me in a form of paragraph. Do not add or change any information, only use the image as your source of information"
EQUATION_PROMPT = "Return me the equation given in the image. Explain the given equation in a paragraph. Do not change or add any text in when writting the equation. The return format will be: \n Equation: '....' \n Description: '..."
