from typing import Any, Dict, Iterable

def reduce(iterable: Iterable[Any], reducers: Dict[Any, Any]) -> Dict[Any, Any]: ...
def reduce_with_grouping(group_id: str, iterable: Iterable[Any], reducers: Dict[Any, Any]) -> Dict[str, Dict[Any, Any]]: ...

