
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-27T17:23:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f4e2b41ee6df19e714a0d76fb0991764792d049",
 "version": "5.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
