class UserIdentifier: ...

class UidIdentifier(UserIdentifier):
    def __init__(self, uid) -> None: ...
    @property
    def uid(self): ...

class EmailIdentifier(UserIdentifier):
    def __init__(self, email) -> None: ...
    @property
    def email(self): ...

class PhoneIdentifier(UserIdentifier):
    def __init__(self, phone_number) -> None: ...
    @property
    def phone_number(self): ...

class ProviderIdentifier(UserIdentifier):
    def __init__(self, provider_id, provider_uid) -> None: ...
    @property
    def provider_id(self): ...
    @property
    def provider_uid(self): ...
