GRANT USAGE ON SCHEMA qa TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA qa GRANT SELECT ON TABLES TO xdb_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA qa GRANT SELECT, UPDATE, INSERT ON TABLES TO xdb_logger;
ALTER DEFAULT PRIVILEGES IN SCHEMA qa GRANT ALL ON TABLES TO xdb_admin;


GRANT SELECT ON ALL TABLES IN SCHEMA qa TO xdb_viewer;
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA qa TO xdb_logger;
GRANT CREATE ON SCHEMA qa TO xdb_admin;
GRANT ALL ON ALL TABLES IN SCHEMA qa TO xdb_admin;