# -*- encoding: utf-8 -*-

ROOT_PATH_KEY = 'ROOT_PATH'
ADMIN_PASSWORD_KEY = 'ADMIN_PASSWORD'
ADMIN_USERNAME_KEY = 'ADMIN_USERNAME'
DEFAULT_PASSWORD_KEY = '123456'
DEFAULT_USERNAME_KEY = 'admin'
HTTP_SERVER_FORK_KEY = 'HTTP_SERVER_FORK'
DEFAULT_HTTP_SERVER_FORK_KEY = False

CIPHER_CIPHERTEXT_KEY = 'CIPHERTEXT'
CIPHER_PRIVATE_KEY_KEY = 'PRIVATE_KEY'

FUNCTION_SELF_KEY = 'self'
FUNCTION_RPC_KEY = 'RpcFunction'
FUNCTION_WORK_KEY = 'WorkerFunction'

FUNCTION_PARAM_NAME_KEY = 'param_name'
FUNCTION_PARAM_DEFAULT_VALUE_KEY = 'default_value'

PROXY_RPC_KEY = 'rpc'
PROXY_NAME_KEY = 'pyrpc_schedule'
PROXY_METHOD_NAME_KEY = 'call'

NAME_KEY = 'name'
SERVICE_PID_KEY = 'service_pid'
SERVICE_NAME_KEY = 'service_name'
SERVICE_IPADDR_KEY = 'service_ipaddr'
SERVICE_VERSION_KEY = 'service_version'
SERVICE_FUNCTIONS_KEY = 'service_functions'

WORKER_PID_KEY = 'worker_pid'
WORKER_NAME_KEY = 'worker_name'
WORKER_IPADDR_KEY = 'worker_ipaddr'
WORKER_VERSION_KEY = 'worker_version'
WORKER_FUNCTIONS_KEY = 'worker_functions'
WORKER_MAX_PROCESS_KEY = 'worker_max_process'
WORKER_RUN_PROCESS_KEY = 'worker_run_process'

TASK_BODY_KEY = 'body'
TASK_ID_KEY = 'task_id'
TASK_STATUS_KEY = 'status'
TASK_SOURCE_ID_KEY = 'source_id'
TASK_IS_SUB_TASK_KEY = 'is_sub_task'
TASK_IS_SUB_TASK_ALL_FINISH_KEY = 'is_sub_task_all_finish'

TASK_QUEUE_NAME_KEY = 'queue_name'
TASK_WEIGHT_KEY = 'weight'
TASK_DEFAULT_WEIGHT = 1

TASK_WAIT_STATUS_KEY = 'wait'
TASK_STOP_STATUS_KEY = 'stop'
TASK_ERROR_STATUS_KEY = 'error'
TASK_RUN_STATUS_KEY = 'running'
TASK_SUCCESS_STATUS_KEY = 'success'
TASK_ERROR_MESSAGE_KEY = 'error_message'

TASK_END_TIME_KEY = 'end_time'
TASK_START_TIME_KEY = 'start_time'
TASK_CREATE_TIME_KEY = 'create_time'

CONFIG_MONGO_KEY = 'MONGODB_CONFIG'
CONFIG_RABBIT_KEY = 'RABBITMQ_CONFIG'
CONFIG_ROOT_PATH_KEY = 'ROOT_PATH'
CONFIG_AMQP_URI_KEY = 'AMQP_URI'
CONFIG_LOGS_PATH_KEY = 'logs'

MONGO_DBNAME_KEY = 'PYRPC-SCHEDULE'

SOCKET_BIND_IP = '8.8.8.8'
SOCKET_BIND_PORT = 80
SOCKET_SHUTDOWN_SLEEP = 2

CONFIG_DEFAULT_TIMEZONE = 'Asia/Shanghai'
CONFIG_DEFAULT_FORMAT = '%Y%m%d%H%M%S'

NODE_IPADDR_KEY = 'ipaddr'

TABLE_NAME_NODES = 'NODES'
TABLE_NAME_TASKS = 'TASK_LIST'
TABLE_NAME_SERVICES = 'SERVICES'

LOG_LEVEL_KEY = 'level'
LOG_TASK_ID_KEY = 'task_id'
LOG_MESSAGE_KEY = 'message'
LOG_FILENAME_KEY = 'filename'
LOG_CALLER_LINES_KEY = 'caller_lines'
LOG_CALLER_FILENAME_KEY = 'caller_filename'

SYSTEM_SERVICE_NAME_KEY = 'proxy_system_server'
SYSTEM_DEFAULT_SCHEDULE_TIME_KEY = 'DEFAULT_SCHEDULE_TIME'
SYSTEM_DEFAULT_SCHEDULE_TIME = 10
