# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/musique/musique.models.ipynb.

# %% auto 0
__all__ = ['QuestionAnsweringResult']

# %% ../../nbs/musique/musique.models.ipynb 3
from pydantic import BaseModel, Field

# %% ../../nbs/musique/musique.models.ipynb 4
class QuestionAnsweringResult(BaseModel):
    """Data model for answering the question."""

    reasoning: str = Field(description="Multi-hop reasoning for the answer.")
    answer: str = Field(description="The answer to the question in 2-4 words.")
    raw_output: str = Field(description="The raw output from the model.")
