import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_f9fb8e2b38(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_bf7637b0b5():spartaqube_cli.list()
@app.command()
def sparta_4a517bd888():spartaqube_cli.sparta_4a517bd888()
@app.command()
def sparta_111441f17a():print('Hello world!')
if __name__=='__main__':app()