#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2406-142-g5ab7a499"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2406
#define NETGEN_VERSION_TWEAK 142
#define NETGEN_VERSION_HASH "g5ab7a499"
#endif // NETGEN_VERSION_HPP_INCLUDED
