GRANT USAGE ON SCHEMA ref TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA ref GRANT SELECT ON TABLES TO xdb_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA ref GRANT SELECT, UPDATE, INSERT ON TABLES TO xdb_logger;
ALTER DEFAULT PRIVILEGES IN SCHEMA ref GRANT ALL ON TABLES TO xdb_admin;


GRANT SELECT ON ALL TABLES IN SCHEMA ref TO xdb_viewer;
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA ref TO xdb_logger;
GRANT CREATE ON SCHEMA ref TO xdb_admin;
GRANT ALL ON ALL TABLES IN SCHEMA ref TO xdb_admin;
