# generated by datamodel-codegen:
#   filename:  location.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class Location:
    """Location in code source."""

    filename: str
    """
    File name.
    """
    lineno: int
    """
    Line number.
    """
