# generated by datamodel-codegen:
#   filename:  test_directory.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class TestDirectory:
    """A collected test directory."""

    node_id: str
    """
    The node ID of the directory.
    """
    name: str
    """
    The directory name.
    """
    path: str
    """
    The directory path.
    """
    node_type: str = "directory"
    """
    The node type. Always set to 'directory'.
    """
