class formula:
    def add(a,b):
        return a+b
    def subtract(a,b):
        return a-b
    def divide(a,b):
        return a/b
    def multi(a,b):
        return a*b
    def mod(a,b):
        return a%b
    def power(a,b):
        return a**b   
    def halo():
        return "halo"