GRANT USAGE ON SCHEMA dem TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA dem GRANT SELECT ON TABLES TO xdb_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA dem GRANT SELECT, UPDATE, INSERT ON TABLES TO xdb_logger;
ALTER DEFAULT PRIVILEGES IN SCHEMA dem GRANT ALL ON TABLES TO xdb_admin;


GRANT SELECT ON ALL TABLES IN SCHEMA dem TO xdb_viewer;
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA dem TO xdb_logger;
GRANT CREATE ON SCHEMA dem TO xdb_admin;
GRANT ALL ON ALL TABLES IN SCHEMA dem TO xdb_admin;