
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-26T11:29:09+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "85c43a9d0fdf1b6c6a997ffbceb993bff88527e9",
 "version": "1.0.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
