# This file was auto-generated by Fern from our API Definition.

from .generic_payment_rail_request import GenericPaymentRailRequest
import typing
from ...invoice_types.types.bank_delivery_method import BankDeliveryMethod
import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2


class BankPaymentRailRequest(GenericPaymentRailRequest):
    available_delivery_methods: typing.Optional[typing.List[BankDeliveryMethod]] = pydantic.Field(
        alias="availableDeliveryMethods", default=None
    )
    default_delivery_method: typing.Optional[BankDeliveryMethod] = pydantic.Field(
        alias="defaultDeliveryMethod", default=None
    )

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
