
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-28T09:49:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7bddbc83a54331b512fbf0ae5a008cdb1958fdff",
 "version": "2.56.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
