# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.resourcecontrollerk8v3_job_execution import Resourcecontrollerk8v3JobExecution

class TestResourcecontrollerk8v3JobExecution(unittest.TestCase):
    """Resourcecontrollerk8v3JobExecution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Resourcecontrollerk8v3JobExecution:
        """Test Resourcecontrollerk8v3JobExecution
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Resourcecontrollerk8v3JobExecution`
        """
        model = Resourcecontrollerk8v3JobExecution()
        if include_optional:
            return Resourcecontrollerk8v3JobExecution(
                details = '',
                ended = '',
                id = '',
                job_id = '',
                modified = '',
                name = '',
                started = '',
                status = ''
            )
        else:
            return Resourcecontrollerk8v3JobExecution(
        )
        """

    def testResourcecontrollerk8v3JobExecution(self):
        """Test Resourcecontrollerk8v3JobExecution"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
