# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.api.edge_scheduler_service_api import EdgeSchedulerServiceApi


class TestEdgeSchedulerServiceApi(unittest.TestCase):
    """EdgeSchedulerServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EdgeSchedulerServiceApi()

    def tearDown(self) -> None:
        pass

    def test_edge_scheduler_service_get_edge_query_status(self) -> None:
        """Test case for edge_scheduler_service_get_edge_query_status

        Summary: Get edge query status Description: Get the status of a queued edge query
        """
        pass

    def test_edge_scheduler_service_monitoring_pending_request_for_edge_query(self) -> None:
        """Test case for edge_scheduler_service_monitoring_pending_request_for_edge_query

        Summary: Monitor for a pending edge query request Description: monitor edge query pending request
        """
        pass

    def test_edge_scheduler_service_schedule_edge_query(self) -> None:
        """Test case for edge_scheduler_service_schedule_edge_query

        Summary: Schedule an edge query  Description: Schedule an edge query via data warehouse queue
        """
        pass


if __name__ == '__main__':
    unittest.main()
