# coding: utf-8

"""
    IBM Guardium Data Security Center

    Use Guardium Data Security Center SDK (application programming interfaces) to interact with other applications, such as Guardium Data Protection, universal connectors, and Guardium Data Security Center reports.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ibm_gdsc_sdk_saas.models.resourcecontrollerk8v3_container_resources import Resourcecontrollerk8v3ContainerResources

class TestResourcecontrollerk8v3ContainerResources(unittest.TestCase):
    """Resourcecontrollerk8v3ContainerResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Resourcecontrollerk8v3ContainerResources:
        """Test Resourcecontrollerk8v3ContainerResources
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Resourcecontrollerk8v3ContainerResources`
        """
        model = Resourcecontrollerk8v3ContainerResources()
        if include_optional:
            return Resourcecontrollerk8v3ContainerResources(
                limits = ibm_gdsc_sdk_saas.models.container_resources_quantity_contains_the_resource_quantities_of_container.ContainerResourcesQuantity contains the resource quantities of container(
                    cpu = '', 
                    memory = '', ),
                requests = ibm_gdsc_sdk_saas.models.container_resources_quantity_contains_the_resource_quantities_of_container.ContainerResourcesQuantity contains the resource quantities of container(
                    cpu = '', 
                    memory = '', )
            )
        else:
            return Resourcecontrollerk8v3ContainerResources(
        )
        """

    def testResourcecontrollerk8v3ContainerResources(self):
        """Test Resourcecontrollerk8v3ContainerResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
