
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-27T17:41:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bf29fd5f447e64b38580f35d42aac8ce0aec33bb",
 "version": "0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
