GRANT USAGE ON SCHEMA surf TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA surf GRANT SELECT ON TABLES TO xdb_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA surf GRANT SELECT, UPDATE, INSERT ON TABLES TO xdb_logger;
ALTER DEFAULT PRIVILEGES IN SCHEMA surf GRANT ALL ON TABLES TO xdb_admin;


GRANT SELECT ON ALL TABLES IN SCHEMA surf TO xdb_viewer;
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA surf TO xdb_logger;
GRANT CREATE ON SCHEMA surf TO xdb_admin;
GRANT ALL ON ALL TABLES IN SCHEMA surf TO xdb_admin;