import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_d8550c5e4a(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_b0b6a01ee8():spartaqube_cli.list()
@app.command()
def sparta_2c723d7e56():spartaqube_cli.sparta_2c723d7e56()
@app.command()
def sparta_b371d7eb7c():print('Hello world!')
if __name__=='__main__':app()