from typing import Tuple

def generate_p_g(bits: int) -> Tuple[int, int]: ...
def generate_a_or_b(p: int) -> int: ...
def generate_A_or_B(p: int, g: int, private_key: int) -> int: ...
def generate_shared_key(public_key: int, p: int, private_key: int) -> int: ...
