
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-14T15:22:20+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa30d61411acd98d943f1e0da1a079fb5124ba6b",
 "version": "2.7.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
