EPEP = [
    "EXO•SHOOᵀᴱᴿ࿐",
    "÷{k•Πt•£}÷",
    "ツち⻓ムㄚ乙ㄖツ꧂",
    "『Sᶻ』꧁Leona꧂",
    "ᴿᴶˢ࿐ÝѧN尺¡Ķø࿐",
    "『NOB』вαℓα∂σяヅ™",
    "『TG』 ཌĐʀᴀɢᴏƝད°ᴵᴰᴹ°ツ",
    "۝۩ •ZERO• ۩۝",
    "꧁þαšТΣĻ꧂௶ꣷ",
    "『DwR』➻❥Łøvε😍",
    "『APS』•Oscarツ",
    "ঔ•ᗪένιใ⎠° Vɪя͢ʊ͋S͚ •ঔ",
    "꧁༺J꙰O꙰K꙰E꙰R꙰༻꧂",
    "ST•",
    "『 JW 』•꧁Ivan꧂",
    "『sʜʀᴋ』•ᴮᴬᴰʙᴏʏツ",
    "『ᴹᵛᴸ』Fℓα₥ȏuֆツ",
    "Lᴬ•K o u r u y a m a🌸",
    "{PLN}•JoKeR™",
    "【YWS】 Ꮓϵɾzxᴬᶜ 戈心",
    "꧁ツち⻓ムㄚ乙ㄖツ꧂",
    "✿乂orem࿐⁩",
    "꧁ঔৣ☬☬ঔৣ꧂",
    "꧁▄▄︻̷̿┻̿═━一꧂",
    "GPS×UJANG√",
    "°ᴮᴸᴰ°нυsᴎιツ",
    "꧁Ms. ★๖ۣۜƤriͥภcͣeͫss★꧂",
    "༄ᶦᶰᵈ᭄✿ᴮᴬᴰʙᴏʏツ",
    "Baby•ᴴᵁᴺᵀᴱᴿ࿐",
    "¢єℓ¢ιυѕ",
    "♛Phaňţøm♛",
    "NicK naMe » Leͥgeͣnͫd    ☂️",
    "꧁฿ิีืÅβγ∞ÐθØŁ꧂",
    "INT•ঔৣÐâřҟŦﺂℜêঔৣ",
    "꧁ ༺ HM•GAMING ༻ ꧂",
    "ρнχ•乙ᴮᴬᴰʙᴏʏ乂",
    "꧁༺J꙰O꙰K꙰E꙰R꙰༻꧂",
    "꧁ ༺ HM•GAMING ༻ ꧂",
    "꧁Ms. ★๖ۣۜƤriͥภcͣeͫss★꧂",
    "ঔ•ᗪένιใ⎠° Vɪя͢ʊ͋S͚ •ঔ",
    "꧁✮ꌗꍏꌩꍏꈤꀘ✮꧂",
    "INT•ঔৣÐâřҟŦﺂℜêঔৣ",
    "༺★BlackSteel★༻",
    "『ᴹᵛᴸ』Fℓα₥ȏuֆツ",
    "꧁●✮CENDEK✮●꧂",
    "꧁✮ꌗꍏꌩꍏꈤꀘ✮꧂",
    "꧁༺༻꧂",
    "꧁༺ɳεאѵαµℓµร☆࿐",
    "《Šûčî|Vāķűm》",
    "꧁༺J꙰O꙰K꙰E꙰R꙰༻꧂",
    "Ｋｏｋ ｍａｔｉ ｃｕｋ",
    "꧁༺nickname༻꧂",
    "『ηя』M͢A͢S͢_tϵr",
    "꧁฿ิีืÅβγ∞ÐθØŁ꧂",
    "〖₩Ā₩〗 ↬ℳѦδØŊ↫  1  0",
    "『Ｗｏｌｆ』•Ｚｅｒｏツ",
    "▄︻̷̿┻̿═━一ØV₵Ⱨ₳Ɽ₭₳⸕şťªİҝερ",
    "ᴷᴵᴺᴳ°OғB͠a͠r²ツ",
    "꧁ঔৣ☠︎$aπ$❦☠︎ঔৣ꧂",
]

FAKTA = [
    "🌾 **Orang yang membayangkan suara baru yang belum pernah didengar, atau menggabungkan sebuah melodi matanya akan bergerak ke kir**",
    "🌾 **Jika kita terkunci diruang yang kedap udara, kita aka lebih dulu mati keracunan co2 dari pada kekerangan o2**",
    "🌾 **Titik merah pada 7-Up logo berasal dari penemunya yang bermata merah. Dia seorang albino.**",
    "🌾 **Di Jerman, tahanan yg ingin meloloskan diri dr penjara adl bukan mrupakn perbuatan ilegal. Krn itu salah1 naluri dasar manusia untuk kebebasan.**",
    "🌾 **Orang sherpa di Nepal menganjurkan orang memakan bawang putih utk mencegah dan mengobati rasa tidak nyaman yg disebabkan ketinggian gunung.**",
    "🌾 **Tanda ’save’ pada Microsoft Office programs menunjukan gambar floppy disk dengan shutter terbalik**",
    "🌾 **Ayam yang sudah terpenggal lehernya masih mampu lari sepanjang lapangan bola sebelum benar-benar mati**",
    "🌾 **ji apel merupakan racun ringan namun tidak berbahaya bagi manusia**",
    "🌾 **Gajah hanya tidur 2 jam dalam sehari**",
    "🌾 **Jika lever manusia berhenti bekerja, manusia akan mati dalam 8 samapai 24 jam**",
    "🌾 **Kecuali manusia dan monyet, semua mamalia buta warna**",
    "🌾 **Orang yang terlalu sering begadang memiliki performa otak seperti 7 tahun lebih tua dari usia aslinya. [dailymail]**",
    "🌾 **Ikan mas yang bunting disebut ‘twit’.**",
    "🌾 **Pada Usia 3 bulan janin manusia mulai terbentuk sidik jari.**",
    "🌾 **Nama paling populer di dunia adalah Muhammad.**",
    "🌾 **Seekor cheetah dapat berlari 76 km per jam.**",
    "🌾 **Kita bisa mematangkan Mangga dengan cepat dengan cara memasukkan ke dalam paperbag bersama dengan pisang matang.**",
    "🌾 **Kulit Zebra adalah putih yang bergaris hitam**",
    "🌾 **Di Perancis, jajanan Arum Manis (Rambut Nenek) disebut “Barbe á Papa” yang berarti “Jenggot Ayah”.**",
    "🌾 **Darah sama kental dengan air laut**",
    "🌾 **Memeluk orang yg disayangi dpt membantu menurunkan tekanan darah, mengurangi stres dan kecemasan, bahkn dpt meningkatkan memori. [Dailymail]**",
    "🌾 **Tikus dan kuda tidak bisa muntah**",
    "🌾 **Menurut penelitian, pria cenderung menurunkan volume suaranya ketika ia berbicara dg seseorang yg ia cintai, sementara perempuan sebaliknya.**",
    "🌾 **Kita bisa mematangkan Mangga dengan cepat dengan cara memasukkan ke dalam paperbag bersama dengan pisang matang.**",
    "🌾 **25% kandungan dalam apel adalah Udara. makanya apel bisa mengapung**",
    "🌾 **RSVP adalah Respondez s’il Vous Plait yang artinya ‘mohon jawaban’**",
    "🌾 **Ada lebih dari 300 bakteri pembentuk karang gigi**",
    "🌾 **Kalajengking bisa dibunuh dengan menyiramnya dengan cuka,mereka akan murka dan menyengat dirinya sendir**",
    "🌾 **Jantung ikan paus biru berdenyut 9 kali dalam semenit**",
    "🌾 **Jika lever manusia berhenti bekerja, manusia akan mati dalam 8 samapai 24 jam**",
    "🌾 **IBM mengatakan bahwa dalam kurun waktu 5 tahun ke depan, komputer bakal mirip manusia yang bisa melihat, mendengar, mencium dan merasakan.**",
    "🌾 **Di Bumi, satu tahun adalah 365 hari. Di planet Merkurius satu tahun adalah 2 hari**",
    "🌾 **Sapi tidak punya gigi atas**",
    "🌾 **rdiri lama tanpa menekuk lutuk sama sekali akan membuat kita pingsan**",
    "🌾 **Kebiasaan sibuk memotret dan mengunggah foto makanan di sosial media, beresiko seseorang menjadi gendut. [Dr. Valerie Taylor]**",
    "🌾 **Darah sama kental dengan air laut**",
    "🌾 **Orang yang menggunakan tangan kanan, kira-kira, 9 tahun lebih panjang umur dari orang kidal**",
    "🌾 **Riset membuktikan, memakan pisang bisa menambah daya ingat**",
    "🌾 **Mangunyah permen karet saat mengupas bawang mencegah kita menangis**",
    "🌾 **Kiwi ditetapkan sebagai buah kebangsaan di Cina**",
    "🌾 **Kuku ibu jari tumbuh lambat dan kuku jari tengah yang tercepat.**",
    "🌾 **Mahluk yang bisa tersipu-sipu hanya manusia**",
    "🌾 **Hormon Cinta hanya bertahan 4 tahun, sisanya dorongan seks. [penelitian di University of Mexico]**",
    "🌾 **Mengoleskan jeruk nipis dapat mencerahkan bagian lutut / siku yang hitam.**",
    "🌾 **Hanya dengan mengurangi brightness dari televisi, anda mampu berhemat lebih dari Rp 1,5 juta setahun. [kompas]**",
    "🌾 **Kutu rambut sebenarnya lebih suka hidup di kulit kepala yang bersih dari pada yang kotorUmur dari capung adalah 24 jam**",
    "🌾 **Terdapat hampir 50 jenis kangguru.**",
    "🌾 **Tangan kanan orang hidup lebih lama dari tangan kiri.**",
    "🌾 **Pulau Giliyang di Sumenep, Jawa Timur disebut sbg pulau “Awet Muda” karena pulau ini memiliki kandungan oksigen terbaik di dunia. [tempo co]**",
    "🌾 **Unta punya 3 kelopak mata.**",
    "🌾 **Tiga monyet bijak punya nama: Mizaru (See no evil), Mikazaru (Hear no evil), and Mazaru (Speak no evil).**",
    "🌾 **Gajah satu-satunya hewan yang tidak bisa meloncat**",
    "🌾 **Kuda Nil kentut lewat mulut.**",
    "🌾 **Pemogokan cahaya di bumi sekitar 6.000 kali per menit.**",
    "🌾 **Di zaman penjajahan Belanda, hukuman orang yg berzina adlh ditangkap dan dicorengkan arang pd hidungnya. Inilah asal usul “Hidung Belang”.**",
    "🌾 **IBM mengatakan bahwa dalam kurun waktu 5 tahun ke depan, komputer bakal mirip manusia yang bisa melihat, mendengar, mencium dan merasakan.**",
    "🌾 **Perut memproduksi lapisan lendir setiap dua minggu agar perut tidak mencerna organnya sendiri.**",
    "🌾 **Tertawa dapat meningkatkan aktivitas antibodi sekitar 20%, juga membantu untuk menghancurkan virus dan sel-sel tumor.**",
    "🌾 **makan plum membantu meningkatkan penyerapan zat besi dalam tubuh**",
    "🌾 **Ilmu tentang perkembangan apel disebut Pomology**",
    "🌾 **Coklat meleleh dalam mulut karena titik lelehnya adalah 35 derajat celcius**",
    "🌾 **Venus dan Uranus adalah planet di tata surya kita yang berputar melawan jarum jam. Jadi matahari terbit dari barat di planet ini.**",
    "🌾 **13% orang di dunia adalah kidal**",
    "🌾 **Jaguar takut pada anjing**",
    "🌾 **Pita karet terpanjang adalah di kulkas.**",
    "🌾 **Tanduk badak terbuat dari rambutnya yang mengeras**",
    "🌾 **Ada sekitar 10ribu jenis apel di dunia Kutu rambut sebenarnya lebih suka hidup di kulit kepala yang bersih dari pada yang kotor**",
    "🌾 **salah satu spesies markisa yang buahnya berwarna ungu bisa melakukan fertilisasi sendiri**",
    "🌾 **Kentut sapi termasuk penyebab utama global warming**",
    "🌾 **Tikus dan kuda tidak bisa muntah**",
    "🌾 **Sekitar 180 juta kartu Valentine tersebar per tahunnya.**",
    "🌾 **Telur segar tenggelam diair, telur yang kadaluarsa mengambang**",
    "🌾 **Mangunyah permen karet saat mengupas bawang mencegah kita menangis**",
    "🌾 **Jika semua emas dalam laut ditambang, setiap manusia didunia bisa mendapat emas 20 kg masing2.**",
    "🌾 **Pria kehilangan 40 helai rambut tiap hari. wanita 70 helai.**",
    "🌾 **Mangunyah permen karet saat mengupas bawang mencegah kita menangis**",
    "🌾 **Saat kita bertahan hidup dan tidak ada bahan makanan, sabuk kulit dan sepatu keds adalah makanan terbaik untuk dimakan karena mengandung cukup gizi untuk hidup sementara.**",
    "🌾 **Titik diatas huruf i disebut ‘title’**",
    "🌾 **Pada abad pertengahan di Eropa, garam sangat mahal harganya, sehingga disebut sebagai “emas putih”.**",
    "🌾 **A “jiffy” is the scientific name for 1/100th of a second.**",
    "🌾 **Amerika telah memiliki 30,30% bandara di dunia & India hanya 0,70%.**",
    "🌾 **Umur dari capung adalah 24 jam**",
    "🌾 **Gigi berang-berang tak pernah berhenti tumbuh**",
    "🌾 **Lidah seekor Chameleon adalah dua kali panjang tubuhnya sendiri.**",
    "🌾 **Eropa adalah benua tanpa padang pasir**",
    "🌾 **69% orang Amerika menggunakan internet dan hanya 5,5% dari India.**",
    "🌾 **Secara fisik, babi tidak bisa melihat ke langit**",
    "🌾 **Pemantik ditemukan sebelum korek api**",
    "🌾 **Dry Ice tidak meleleh, tapi menguap**",
    "🌾 **Nama Artic (kutub utara) berarti beruang dalam bahasa Yunani (Arktos), dan memang beruang kutub hanya ada di kutub utara**",
    "🌾 **Seseorang masih akan sadar selama 8 detik setelah dipenggal**",
    "🌾 **Albert Einstein dan Charles Darwin,keduanya menikah dengan sepupu pertama mereka (Elsa Löwenthal dan Emma Wedgewood).**",
    "🌾 **98% dari perkosaan dan pembunuhan dilakukan oleh keluarga dekat atau teman korban.**",
    "🌾 **Gazzarella adalah keju mozzarella yang terbuat dari susu kucing. 61. Rata-rata orang melihat / mengecek ponselnya sekitar 150 kali sehari. (Laporan Nokia pada MindTrek 2010)**",
    "🌾 **Rat-rata orang bergerak 40 kali dalam tidurnya**",
    "🌾 **nga pohon markisa adalah Bunga kebangsaan negara Paraguay**",
    "🌾 **Topeng tokoh Michael Myers di film horor ‘Helloween’ sebenernya topeng tokoh Captain Kirk (Star Trek) yang di cat putih, karena kurang dana**",
    "🌾 **Kucing berkeringat melalui telapak kakinya (terutama saat mendengar gonggongan anjing)**",
    "🌾 **Tehnik mengaduk terbaik bukan dengan gerakan memutar, tapi dengan gerakan huruf W**",
    "🌾 **Nomer “172? dapat ditemukan pada uang kertas 5 dollar amerika, pada gambar semak-semak dibawah Lincoln Memorial.**",
    "🌾 **Shuttlecock untuk badminton harus punya 14 bulu.**",
    "🌾 **Memakan seledri membuang kalori lebih banyak dari pada kalori yang terkandung dalam seledri itu sendiri**",
    "🌾 **Kulit Plum dipercaya memiliki efek Laxative**",
    "🌾 **rung umumnya tidak berkicau apabila mereka hinggap di tanah (Hummingbirdworld).**",
    "🌾 **Pendeta Mesir kuno mencabuti setiap helai rambut dan bulu dari badan mereka.**",
    "🌾 **Nama asli butterfly (kupu-kupu) adalah flutterby.**",
    "🌾 **Dalam setiap inci persegi permukaan smartphone terdapat skitar 25.107 kuman, artinya smartphone lebih kotor dr kloset. [Laporan dr Proporta]**",
    "🌾 **Radiasi dari 1 batang rokok sama dgn radiasi 2000x X-ray**",
    "🌾 **Tanduk badak terbuat dari rambutnya yang mengeras**",
    "🌾 **Kelelawar selalu belok kiri jika terbang keluar gua**",
    "🌾 **Ubur-ubur terdiri dari 95% air**",
    "🌾 **Riset membuktikan bahwa makan apel bisa mengurangi risiko kena kanker**",
    "🌾 **Julius Caesar tewas dengan 23 tikaman**",
    "🌾 **Orang yang berusia di atas 100 di AS meningkat dari 4.000 pada tahun 1960 menjadi 55.000 pada tahun 1995.**",
    "🌾 **Tidak ada bukti yang pasti siapa yang membangun Taj Mahal.**",
    "🌾 **Cahaya matahari mencapai bumi membutuhkan waktu sekitar 8 jam 3 detik.**",
    "🌾 **IBM mengatakan bahwa dalam kurun waktu 5 tahun ke depan, komputer bakal mirip manusia yang bisa melihat, mendengar, mencium dan merasakan.**",
    "🌾 **Telur segar tenggelam diair, telur yang kadaluarsa mengambang**",
    "🌾 **Ken Edwards seorang pria asal Inggris memegang rekor Guinness untuk makan 36 kecoa dalam 1 menit.**",
    "🌾 **mangga masih 1 family dengan tanaman Poison Ivy**",
    "🌾 **Pisang mengandung vitamin B6 yang bisa mengontrol kadar gula dalam darah, dan membangkitkan mood**",
    "🌾 **Microwave ditemukan setelah seorang ilmuan yang berjalan melewati tabung radar mendapati permen coklatnya meleleh disakunya.**",
    "🌾 **Hangry adalah penggabungan kata dari “Hungry” dan “Angry”, di pakai ketika anda sedang lapar dan marah.**",
    "🌾 **Nama asli butterfly (kupu-kupu) adalah flutterby.**",
    "🌾 **Sekitar 14% pecandu yang menggunakan jarum suntik, positif HIV.**",
    "🌾 **Karena langkanya logam, piala Oscars yang dibagikan pada perang dunia ke II terbuat dari kayu**",
    "🌾 **Ketika kita sedang jatuh cinta, otak akan memproduksi dopamin ekstra, bahan kimia yang membuat seseorang menjadi gembira berlebihan.**",
    "🌾 **Merebus telur burung unta butuh waktu 40 menit.**",
    "🌾 **Wanita yang sedang stres selama kehamilannya cenderung melahirkan anak-anak yang pemarah. [Institute of Psychiatry, King College London]**",
    "🌾 **nanas yang belum matang adalah racun**",
    "🌾 **Kucing rumah benci bau lemon dan semua yang berbau sitrus**",
    "🌾 **Nama “Gorila” berasal dari kata Yunani “Gorillai” yang berarti “perempuan berbulu”.**",
    "🌾 **Hanya 3 malaikat, Gabriel, Michael dan Lucifer yang disebut dalam injil.**",
    "🌾 **Air laut di samudra Atlantik lebih asin dari pada di samudra Pasifik**",
    "🌾 **gian dalam kulit pisang juga bisa digunakan untuk menghilangkan gatal bekas gigitan nyamuk dengan cara menggosokkannya**",
    "🌾 **Mangunyah permen karet saat mengupas bawang mencegah kita menangis**",
    "🌾 **Kode Telephone Internasional untuk Antartica adalah 672.**",
    "🌾 **Musik memiliki kemampuan untuk memperbaiki kerusakan otak serta mengembalikan kenangan yang hilang. [cracked .com]**",
    "🌾 **25% kandungan dalam apel adalah Udara. makanya apel bisa mengapung**",
    "🌾 **ku Guinness Book of Records memegang rekor sebagai buku yang paling banyak dicuri dari perpustakaan**",
    "🌾 **Kulit Zebra adalah putih yang bergaris hitam**",
    "🌾 **Unta punya 3 kelopak mata.**",
    "🌾 **David Sarnoff adalah orang yang menerima sinyal Titanic dan meyelamatkan ratusan nyawa. Dia akhirnya menjadi kepala jaringan radio, the National Broadcasting Company (NBC).**",
    "🌾 **pohon kelapa entah kenapa disebut “Tree of Life”**",
    "🌾 **Orang yang merasa kesepian memiliki kemungkinan mengalami kepikunan 70-80% lebih tinggi. (Journal of Neurosurgery Neurologi and Psychiatry)**",
    "🌾 **Mengunyah permen karet dapat meningkatkan kemampuan berpikir cepat dan kewaspadaan hingga 10 persen. [Jurnal Brain and Cognition]**",
    "🌾 **Kalajengking bisa dibunuh dengan menyiramnya dengan cuka,mereka akan murka dan menyengat dirinya sendir**",
    "🌾 **Hanya dengan mengurangi brightness dari televisi, anda mampu berhemat lebih dari Rp 1,5 juta setahun. [kompas]**",
    "🌾 **Orang yang cerdas memiliki kadar seng dan tembaga di rambut mereka**",
]

ISLAMIC = [
    "📖 **Karena yang hanya pamer foto mesra disosmed akan kalah dengan yang cantumin foto di buku nikah**",
    "📖 **Allah maha kuasa dan Allah maha tahu, jadi meskipun aku dan kamu tidak menjadi kita, insyaallah ini yang terbaik**",
    "📖 **Gak usah bingung seperti apa jodohmu kelak, Insyaallah dia tidak akan jauh daripada sifatmu saat ini**",
    "📖 **Semua pengorbanan dan perjuangan kel akan mendapatkan balasan yang terbaik**",
    "📖 **Aku berharap bisa hidup mendampingimu namun apa daya ternyata diriku tidaklah baik untuk mendampingi dirimu**",
    "📖 **Ya Allah maafkan segala kemaksiatan yang sudah hamba perbuat**",
    "📖 **Sahabat adalah orang yang ikhlas bersama kita dalam senang dan susah dan saling menasehati dalam ketaatan kepada Allah**",
    "📖 **Musibah yang membuatmu kembali kepada Allah lebih baik dari nikmat yang membuatmu lupa kepada Allah**",
    "📖 **Balaslah keburukan dengan kebaikan**",
    "📖 **Untuk yang baru berhijrah jadilah seperti pakaian baru yang senantiasa kita rawat dan jaga agar senantiasa presiden terjaga Jika ia kotor maka akan dibersihkan dari noda**",
    "📖 **Allah maha kuasa dan Allah maha tahu, jadi meskipun aku dan kamu tidak menjadi kita, insyaallah ini yang terbaik**",
    "📖 **Ucapkan alhamdulillah karena bisa jadi itu adalah cara Allah menyapa kita lewat rasa sakit yang kita terima**",
    "📖 **Alhamdulillah atas segala nikmat yang telah engkau berikan**",
    "📖 **Ketika nyawa sudah tiada kemudian Allah menambah-nambah satu hari lagi kesempatan itu hidup niscaya kita akan bertaubat**",
    "📖 **Tambahkan pasangan itu dia bisa membimbing bukan hanya di dunia tapi juga di akhirat**",
    "📖 **Semoga memang dirimulah yang kelak menjadi pendamping hidupku**",
    "📖 **Kunci hidup bahagia adalah Jalani, Nikmati dan Syukuri**",
    "📖 **Salah satu ciri lellaki setia adalah berani menikahi di dia, bukan memacarinya. Apalagi meninggalkannya di kala semua sudah diserahkan**",
    "📖 **Aku menunggumu untuk segera menghalalkanku tapi jika kelak yang datang lebih awal bukan dirimu tapi baik agamanya Mungkin dia yang terbaik untukku**",
    "📖 **Kalau lagi hujan kini biasanya sahabat berdoa minta apa**",
    "📖 **Jangan salahkan orang ketika kamu kecewa, tapi salahkan dirimu sendiri karena terlalu berharap sesuatu yang belum pasti**",
    "📖 **Jangan pernah merasa lebih baik daripada orang lain karena kita tidak tahu seberapa banyak amal kebaikan yang ia tutupi**",
    "📖 **Tak harus kamu yang sempurna, setidaknya kamu yang selalu berusaha istiqpmah di setiap waktu yang kamu punya. Karena kita akan berkerjasama membangun rumah di surga**",
    "📖 **Semoga dalam kesendirian ini bisa bisa betul-betul lolos dalam ujian menahan diri dari lawan jenis**",
    "📖 **Hubungan yang jelas di dalamnya ada pembohongan bagaimana kau akan membangun rumah tangga dengan pribadi seperti itu**",
    "📖 **Jodoh bukan siapa cepat pasti dapt tapu jika Allah telah tetapkan sudah pasti dapat**",
    "📖 **Ku rindu padamu ya rasul Kuingin jumpa Sekedar Saja walau hanya dalam mimpi**",
    "📖 **Apalah gunanya hidup 100 tahun kalau tidak shalat dan tidak mengaji**",
    "📖 **Lebih baik tersindir ketika diingatkan, daripada tidak merasakan apa-apa ketika diingatkan**",
    "📖 **Jangan mati-matian menghias diri untuk menjadi seperfect mungkin. Padahal yang kamu harus selalu jaga dan perbaiki adalah kualitas diri bukan kualitas fisik**",
    "📖 **Akan tiba saatnya sendiri ku menjadi kebahagiaan yang Hakiki**",
    "📖 **Hukuman terberat dari Allah ketika Allah telah menutup diri kita untuk dapat berbuat dan melakukan kebaikan-kebaikan**",
    "📖 **Takkan datang ridha Allah pada hubungan yang melanggar larangan Allah**",
    "📖 **Yang palilng aku takutkan atas umat ini adalah orang berilmu yang munafik**",
    "📖 **Semua itu butuh pengorbanan dan keikhlasan apalagi memilih jalan kebaikan pasti akan ada selalu orang yang bertentangan tetapi Allah takkan pernah menutup Kerinduan bagi mereka yang rela melakukan perubahan**",
    "📖 **Sungguh tak terhitung banyaknya nikmat yang sudah engkau berikan kepada kami ya Allah**",
    "📖 **Sebagian masa depanmu ditentukan oleh Siapa teman bergaulmu**",
    "📖 **Aku berharap bisa menjadi pemimpin yang baik yang memimpin mu dengan iman dan ketaqwaan**",
    "📖 **Dalam mengejar rejeki Janganlah mengajar jumlahnya tetapi kejarlah berkahnya**",
    "📖 **Mencintai dengan sungguh-sungguh memberikan kebahagiaan di hati kita mencintai karena Allah kita mendapat nilai ibadah dan kebahagiaan yang lebih**",
    "📖 **Maka aku ucapkan selamat engkau sukses membuat perasaannya sedikit terluka**",
    "📖 **Terkadang bukan karena kita tahu caranya memuntahkan amarah tapi kita tahu jika makin marah tak akan menyelesaikan masalah**",
    "📖 **Seorang muslimah sejati adalah bisa menanamkan cinta terdalam di hati suaminya bukan pacarnya**",
    "📖 **Ketika seseorang pergi dan tinggalkan kita maka datanglah pada Allah dengan doa dan ibadah kita bersungguh-sungguh kita akan merasakan keindahan dan kasih sayang yang luar biasa**",
    "📖 **Sedekah tidak sama dengan matematika bisa ditambah, dikurang, dibagi dan dikali. Karena sedekah itu akan berlimpah dan berkalilipa kembali kepada kita**",
    "📖 **Siapapun yang merindukan sukses, maka harus bertanya pada dirinya seberapa jauh dan sungguh-sungguh untuk berjuang, karena tiada kesuksesan tanpa perjuangan**",
    "📖 **Sejatinya bukan karena kita hebat tapi Allah yang memudahkan urusan kita**",
    "📖 **Semut akan berkerumun di sekitar gula jika ingin mencari jodoh Shalih Carilah di kumpulan orang Shalih**",
    "📖 **Bila hijrahmu karena Allah, kamu akan terus melangkah walaupun sudah lelah**",
    "📖 **Tak usah tergoda dengan wanita yang lihai memainkan tulisan bedak di mukanya sebab anakmu kelak butuhnya ibu yang berakhlak**",
    "📖 **Yakinlah masalah yang menimpamu saat ini merupakan cara Allah untuk mengingatkanmu agar lebih dekat dengan Allah**",
    "📖 **Kuharap semua doa disetiap sudut panjangku bisa melangit dan terkabulkan**",
    "📖 **Ada cinta yang menghantarkan menuju kemaksiatan, ada juga cinta yang membuat seseorang berubah mencintai hanya karena Allah, saling mencintailah karena Allah**",
    "📖 **Harus disadari oleh wanita muslimah bahwa yang telah menyaksikan Kecantikan adalah suaminya dan para mahromnya**",
    "📖 **Kalau lagi hujan kini biasanya sahabat berdoa minta apa**",
]

MOTIVASI = [
    "🧗 **Kesempatan itu mirip seperti matahari terbit. Kalau kau menunggu terlalu lama, kau bisa melewatkannya**",
    "🧗 **Kegagalan dibuat hanya oleh mereka yang gagal untuk berani, bukan oleh mereka yang berani gagal**",
    "🧗 **Disiplin adalah jembatan antara tujuan dan pencapaian**",
    "🧗 **Lebih baik gagal dalam orisinalitas daripada berhasil meniru**",
    "🧗 **Disiplin adalah jembatan antara tujuan dan pencapaian**",
    "🧗 **Sukses tampaknya terkait dengan tindakan. Orang sukses terus bergerak. Mereka membuat kesalahan, tetapi mereka tidak berhenti**",
    "🧗 **Keberanian adalah penolakan terhadap rasa takut, penguasaan rasa takut, bukan ketiadaan rasa takut**",
    "🧗 **Sukses tampaknya terkait dengan tindakan. Orang sukses terus bergerak. Mereka membuat kesalahan, tetapi mereka tidak berhenti**",
    "🧗 **Hidup kita mulai berakhir saat kita menjadi diam tentang hal-hal yang penting**",
    "🧗 **Kesempatan itu mirip seperti matahari terbit. Kalau kau menunggu terlalu lama, kau bisa melewatkannya**",
    "🧗 **Kegagalan dibuat hanya oleh mereka yang gagal untuk berani, bukan oleh mereka yang berani gagal**",
    "🧗 **Lakukan apa yang harus kamu lakukan sampai kamu dapat melakukan apa yang ingin kamu lakukan**",
    "🧗 **Keberanian adalah penolakan terhadap rasa takut, penguasaan rasa takut, bukan ketiadaan rasa takut**",
    "🧗 **Kegagalan dibuat hanya oleh mereka yang gagal untuk berani, bukan oleh mereka yang berani gagal**",
    "🧗 **Penghargaan paling tinggi bagi seorang pekerja keras bukanlah apa yang dia peroleh dari pekerjaan itu, tapi seberapa berkembang ia dengan kerja kerasnya itu**",
    "🧗 **Jangan tunda pekerjaanmu sampai besok, sementara kau bisa mengerjakannya hari ini**",
    "🧗 **Saya tidak bisa memberimu rumus untuk sukses, tapi saya bisa memberi rumus untuk gagal, yaitu: cobalah untuk menyenangkan semua orang**",
    "🧗 **Sukses adalah tempat persiapan dan kesempatan bertemu**",
    "🧗 **Disiplin adalah jembatan antara tujuan dan pencapaian**",
    "🧗 **Tetapkan tujuan Anda tinggi-tinggi, dan jangan berhenti sampai Anda mencapainya**",
    "🧗 **Hidup kita mulai berakhir saat kita menjadi diam tentang hal-hal yang penting**",
    "🧗 **Tetapkan tujuan Anda tinggi-tinggi, dan jangan berhenti sampai Anda mencapainya**",
    "🧗 **Daripada mengeluh tentang keadaanmu, sibuklah dan buat beberapa yang baru**",
    "🧗 **Orang pesimis melihat kesulitan di setiap kesempatan. Orang yang optimis melihat peluang dalam setiap kesulitan**",
    "🧗 **Sukses tampaknya terkait dengan tindakan. Orang sukses terus bergerak. Mereka membuat kesalahan, tetapi mereka tidak berhenti**",
    "🧗 **Saya tidak bisa memberimu rumus untuk sukses, tapi saya bisa memberi rumus untuk gagal, yaitu: cobalah untuk menyenangkan semua orang**",
    "🧗 **Tetapkan tujuan Anda tinggi-tinggi, dan jangan berhenti sampai Anda mencapainya**",
    "🧗 **Hidup kita mulai berakhir saat kita menjadi diam tentang hal-hal yang penting**",
    "🧗 **Jika rencananya tidak berhasil, ubah rencananya bukan tujuannya**",
    "🧗 **Saya tidak bisa memberimu rumus untuk sukses, tapi saya bisa memberi rumus untuk gagal, yaitu: cobalah untuk menyenangkan semua orang**",
    "🧗 **Daripada mengeluh tentang keadaanmu, sibuklah dan buat beberapa yang baru**",
    "🧗 **Pengalaman adalah guru yang berat karena dia memberikan tes terlebih dahulu, kemudian pelajarannya**",
    "🧗 **Cara terbaik untuk memulai adalah dengan berhenti berbicara dan mulai melakukan**",
    "🧗 **Jenius adalah satu persen inspirasi dan sembilan puluh sembilan persen keringat**",
    "🧗 **Jangan biarkan kemarin menyita terlalu banyak hari ini**",
    "🧗 **Penghargaan paling tinggi bagi seorang pekerja keras bukanlah apa yang dia peroleh dari pekerjaan itu, tapi seberapa berkembang ia dengan kerja kerasnya itu**",
    "🧗 **Tetapkan tujuan Anda tinggi-tinggi, dan jangan berhenti sampai Anda mencapainya**",
    "🧗 **Jika saya punya waktu enam jam untuk menebang pohon, saya akan menghabiskan empat jam pertama mengasah kapak**",
    "🧗 **Jangan tunda pekerjaanmu sampai besok, sementara kau bisa mengerjakannya hari ini**",
    "🧗 **Waktu lebih berharga daripada uang. Kamu bisa mendapatkan lebih banyak uang, tetapi kamu tidak bisa mendapatkan lebih banyak waktu**",
    "🧗 **Jenius adalah satu persen inspirasi dan sembilan puluh sembilan persen keringat**",
    "🧗 **Lakukan apa yang harus kamu lakukan sampai kamu dapat melakukan apa yang ingin kamu lakukan**",
    "🧗 **Kegagalan tidak akan pernah menyusul jika tekad untuk sukses cukup kuat**",
    "🧗 **Optimistis adalah salah satu kualitas yang lebih terkait dengan kesuksesan dan kebahagiaan daripada yang lain**",
    "🧗 **Tidak ada kata terlambat untuk menjadi dirimu yang seharusnya**",
    "🧗 **Kesempatan itu mirip seperti matahari terbit. Kalau kau menunggu terlalu lama, kau bisa melewatkannya**",
    "🧗 **Daripada mengeluh tentang keadaanmu, sibuklah dan buat beberapa yang baru**",
    "🧗 **Pengalaman adalah guru yang berat karena dia memberikan tes terlebih dahulu, kemudian pelajarannya**",
    "🧗 **Orang pesimis melihat kesulitan di setiap kesempatan. Orang yang optimis melihat peluang dalam setiap kesulitan**",
    "🧗 **Berani bermimpi, tapi yang lebih penting, berani melakukan tindakan di balik impianmu**",
    "🧗 **Jika rencananya tidak berhasil, ubah rencananya bukan tujuannya**",
    "🧗 **Ketekunan gagal 19 kali dan berhasil pada kesempatam yang ke-20**",
    "🧗 **Waktu lebih berharga daripada uang. Kamu bisa mendapatkan lebih banyak uang, tetapi kamu tidak bisa mendapatkan lebih banyak waktu**",
    "🧗 **Cara terbaik untuk memulai adalah dengan berhenti berbicara dan mulai melakukan**",
    "🧗 **Jangan tunda pekerjaanmu sampai besok, sementara kau bisa mengerjakannya hari ini**",
    "🧗 **Tetapkan tujuan Anda tinggi-tinggi, dan jangan berhenti sampai Anda mencapainya**",
    "🧗 **Lakukan lebih banyak untuk dunia daripada untuk dirimu**",
]

ANIMEK = [
    {
        "🎁 **Quotes": "Kata-kata dapat menyakiti seseorang. Meskipun kau menyesalinya, kau takkan pernah bisa menarik kembali (kata-kata yang telah kau ucapkan).**",
        "🌹 **Character": "Jun Naruse**",
        "🍁 **Anime": "Kokoro ga Sakebitagatterunda.**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Jika peringkat (dalam pertandingan) membuatmu khawatir. (Tenang saja) kau sudah mendapatkan peringkat pertama di dalam hatiku.**",
        "🌹 **Character": "Keima Katsuragi**",
        "🍁 **Anime": "Kami nomi zo Shiru Sekai**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Para penguasa itu seperti hewan ternak yang hanya memakan jabatan.**",
        "🌹 **Character": "Marrine Kreische**",
        "🍁 **Anime": "Grancrest Senki**",
        "🍁 **Episode": "Episode 20**",
    },
    {
        "🎁 **Quotes": "Dia lebih mencemaskan temannya daripada dirinya sendiri. Dia lebih mementingkan temannya. Aku menghormati perasaannya. Jika kau ingin mencapai sesuatu, kau harus berusaha keras untuk mencapai semuanya.**",
        "🌹 **Character": "Subaru Natsuki**",
        "🍁 **Anime": "Re:Zero kara Hajimeru Isekai Seikatsu**",
        "🍁 **Episode": "Episode 9**",
    },
    {
        "🎁 **Quotes": "Karena aku tak memiliki harta sama sekali, yang bisa aku berikan hanyalah waktu, perasaan, masa depan, kehidupan dan hal-hal samar lainnya.**",
        "🌹 **Character": "Hachiman Hikigaya**",
        "🍁 **Anime": "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Kan**",
        "🍁 **Episode": "Episode 11**",
    },
    {
        "🎁 **Quotes": "Suna, kali ini aku tak akan salah lagi. Tapi, jika aku kehilangan arah dan mulai mengambil jalan yang salah, tolong pukul aku.**",
        "🌹 **Character": "Takeo Gouda**",
        "🍁 **Anime": "Ore Monogatari!!**",
        "🍁 **Episode": "Episode 24**",
    },
    {
        "🎁 **Quotes": "Kejujuran yang kau perlihatkan saat kau mengungkapkan perasaanmu benar-benar murni dan manis.**",
        "🌹 **Character": "Suzuno Kamazuki**",
        "🍁 **Anime": "Hataraku Maou-sama!**",
        "🍁 **Episode": "Episode 8**",
    },
    {
        "🎁 **Quotes": "Kami (berdua) yang telah terluka saling mengharapkan hal yang sama.Jika besok kau mati, maka aku tidak keberatan jika besok hidupku juga berakhir.Jika hari ini kau tetap hidup, aku pun juga akan hidup.**",
        "🌹 **Character": "Koyomi Araragi**",
        "🍁 **Anime": "Kizumonogatari III: Reiketsu-hen**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Kalau ada gadis cantik yang sedang kesulitan, pria baik (pasti) akan menyelamatkannya.**",
        "🌹 **Character": "Rita Ainsworth**",
        "🍁 **Anime": "Sakurasou no Pet na Kanojo**",
        "🍁 **Episode": "Episode 9**",
    },
    {
        "🎁 **Quotes": "Mereka bilang orang itu bisa berubah, tapi apa yang seperti itu bisa terjadi? Jika mereka (manusia) memutuskan untuk terbang, pasti akan tumbuh sayap? Aku tak berpikir seperti itu. Kau tak perlu merubah dirimu, (tapi) rubahlah cara berfikirmu. Kau harus menjadi dirimu sendiri. Kau harus membuat cara terbangmu sendiri, meskipun kau masih tetap menjadi dirimu sendiri.**",
        "🌹 **Character": "Sora**",
        "🍁 **Anime": "No Game No Life**",
        "🍁 **Episode": "Episode 9**",
    },
    {
        "🎁 **Quotes": "Yakinlah pada dirimu sendiri! Semuanya akan baik baik saja! Semakin keras kau berusaha, kau pasti akan semakin beruntung!**",
        "🌹 **Character": "Miyano**",
        "🍁 **Anime": "Tanaka-kun wa Itsumo Kedaruge**",
        "🍁 **Episode": "Episode 12**",
    },
    {
        "🎁 **Quotes": "Mengetahui orang lain mau membaca tulisanku yang kusukai dan mereka memberikan kesan yang cukup bagus itu sangat menyenangkan.**",
        "🌹 **Character": "Yoshiteru Zaimokuza**",
        "🍁 **Anime": "Yahari Ore no Seishun Love Comedy wa Machigatteiru**",
        "🍁 **Episode": "Episode 2**",
    },
    {
        "🎁 **Quotes": "Seluruh tubuhku telah berlumuran darah. Karena aku, puluhan ribu orang telah kehilangan nyawanya. Aku tak pantas hidup bahagia.**",
        "🌹 **Character": "Marrine Kreische**",
        "🍁 **Anime": "Grancrest Senki**",
        "🍁 **Episode": "Episode 20**",
    },
    {
        "🎁 **Quotes": "Hanya karena semua orang melakukan dan mengatakan hal yang sama, itu tak menjamin kebenaran.**",
        "🌹 **Character": "Sakuta Azusagawa**",
        "🍁 **Anime": "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai**",
        "🍁 **Episode": "Episode 3**",
    },
    {
        "🎁 **Quotes": "Temanku akan menang meski kutinggalkan mereka!**",
        "🌹 **Character": "Akiteru Tsukishima**",
        "🍁 **Anime": "Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou**",
        "🍁 **Episode": "Episode 7**",
    },
    {
        "🎁 **Quotes": "Setiap orang memiliki langkah mereka sendiri.**",
        "🌹 **Character": "Miwako Tomobe**",
        "🍁 **Anime": "Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai**",
        "🍁 **Episode": "Episode 12**",
    },
    {
        "🎁 **Quotes": "Semua hal yang terjadi di depanku adalah masalah yang hanya bisa diselesaikan oleh diriku sendiri.**",
        "🌹 **Character": "Hachiman Hikigaya**",
        "🍁 **Anime": "Yahari Ore no Seishun Love Comedy wa Machigatteiru. Zoku**",
        "🍁 **Episode": "Episode 4**",
    },
    {
        "🎁 **Quotes": "Seseorang tidak akan berjuang sekeras itu jika dia tidak menyukainya.**",
        "🌹 **Character": "Keiko Ayano**",
        "🍁 **Anime": "Sword Art Online**",
        "🍁 **Episode": "Episode 4**",
    },
    {
        "🎁 **Quotes": "Yusa-san mencoba membuatku berhenti menyukaimu dan berkata kalau aku akan menyesal nantinya. Tapi, aku menyukaimu dengan kemauanku sendiri. Maka dari itu, suka ataupun tidak suka, aku sendiri yang memutuskannya.**",
        "🌹 **Character": "Chiho Sasaki**",
        "🍁 **Anime": "Hataraku Maou-sama!**",
        "🍁 **Episode": "Episode 8**",
    },
    {
        "🎁 **Quotes": "Mengabdikan diri untuk pendidikan adalah suatu bentuk kerja keras.**",
        "🌹 **Character": "Mayoi Hachikuji**",
        "🍁 **Anime": "Monogatari Series: Second Season**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Aku sangat menyukai kerendahan hatimu yang bahkan tak kausadari telah menjadi daya tarikmu.**",
        "🌹 **Character": "Neko Fujinomiya**",
        "🍁 **Anime": "Masamune-kun no Revenge**",
        "🍁 **Episode": "Episode 6**",
    },
    {
        "🎁 **Quotes": 'Kau tak boleh bilang "hidup sendiri" ketika banyak orang yang mengkhawatirkan dirimu.**',
        "🌹 **Character": "Akari Kawamoto**",
        "🍁 **Anime": "3-gatsu no Lion**",
        "🍁 **Episode": "Episode 11**",
    },
    {
        "🎁 **Quotes": "Di lingkungan orang-orang dewasa, setiap kerja keras akan selalu mendapat imbalan.**",
        "🌹 **Character": "Yoshifumi Nitta**",
        "🍁 **Anime": "Hinamatsuri**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Temanku akan menang meski kutinggalkan mereka!**",
        "🌹 **Character": "Akiteru Tsukishima**",
        "🍁 **Anime": "Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou**",
        "🍁 **Episode": "Episode 7**",
    },
    {
        "🎁 **Quotes": "Kecantikan seorang makhluk itu akan terlihat indah saat mereka masih alami.**",
        "🌹 **Character": "Itsuki Hashima**",
        "🍁 **Anime": "Imouto sae Ireba Ii.**",
        "🍁 **Episode": "Episode 9**",
    },
    {
        "🎁 **Quotes": "Mari kita bersaing secara sehat agar nantinya takkan ada penyesalan diantara kita.**",
        "🌹 **Character": "Crusch Karsten**",
        "🍁 **Anime": "Re:Zero kara Hajimeru Isekai Seikatsu**",
        "🍁 **Episode": "Episode 15**",
    },
    {
        "🎁 **Quotes": "Saling menerima cinta satu sama lain adalah hal yang wajar. Jika dunia melarangnya, aku akan mengubah dunia ini meskipun harus menghancurkannya.**",
        "🌹 **Character": "Theo Cornaro**",
        "🍁 **Anime": "Grancrest Senki**",
        "🍁 **Episode": "Episode 20**",
    },
    {
        "🎁 **Quotes": "Aku tidak peduli! Selama aku bisa terus bersama dengan dirimu, bagiku sudah cukup. Tidak, bahkan itulah yang aku inginkan!**",
        "🌹 **Character": "Koyuki Hinashi**",
        "🍁 **Anime": "Fuuka**",
        "🍁 **Episode": "Episode 11**",
    },
    {
        "🎁 **Quotes": "Aku hanya ingin melihatmu membuktikan bahwa kerja keras pasti membawa hasil yang memuaskan.**",
        "🌹 **Character": "Sorata Kanda**",
        "🍁 **Anime": "Sakurasou no Pet na Kanojo**",
        "🍁 **Episode": "Episode 15**",
    },
    {
        "🎁 **Quotes": "Tugas kami sebagai orang biasa adalah untuk memastikan bahwa potensi yang tak bisa dimengerti itu bisa terwujud.**",
        "🌹 **Character": "Sora**",
        "🍁 **Anime": "No Game No Life**",
        "🍁 **Episode": "Episode 7**",
    },
    {
        "🎁 **Quotes": "Aku memiliki kehidupan yang kosong, tak ada apapun kecuali perasaanku padamu.(Meskipun) aku juga tidak punya pedang, tapi hatiku ingin menjadi seorang kesatria.**",
        "🌹 **Character": "Akitoshi Daimon**",
        "🍁 **Anime": "Sket Dance**",
        "🍁 **Episode": "Episode 41**",
    },
    {
        "🎁 **Quotes": "Melihat seorang murid yang menatap masa depannya itu begitu indah.**",
        "🌹 **Character": "Souma**",
        "🍁 **Anime": "Demi-chan wa Kataritai**",
        "🍁 **Episode": "Episode 10**",
    },
    {
        "🎁 **Quotes": "Mungkin ada kalanya (kau) merasa bingung dan merasa kesal karena kenyataan tidak berjalan sesuai dengan harapan. Tapi, hal yang kau pelajari tidak akan pernah mengkhianatimu.**",
        "🌹 **Character": "Tooru Miyagishi**",
        "🍁 **Anime": "Hanasaku Iroha**",
        "🍁 **Episode": "Episode 21**",
    },
    {
        "🎁 **Quotes": "Aku ingin menikmati hubungan asmara ini, bukan hasilnya.**",
        "🌹 **Character": "Mari Shiina**",
        "🍁 **Anime": "Renai Boukun**",
        "🍁 **Episode": "Episode 2**",
    },
    {
        "🎁 **Quotes": "Tertawa karena baca manga komedi dapat melatih otot perut. Terkejut karena baca manga horor dapat melatih otot punggung. Berdebar-debar karena baca manga romatis dapat melatih otot jantung. Membaca manga edisi khusus setebal 932 halaman dapat melatih otot bisep. Orang-orang yang terlibat dengan manga harus melatih otot dengan manga.**",
        "🌹 **Character": "Ami Kakei**",
        "🍁 **Anime": "Kakushigoto**",
        "🍁 **Episode": "Episode 3**",
    },
    {
        "🎁 **Quotes": "Pemandangan yang kurasa membosankan...Pemandangan di mana Kou-chan berada (ternyata) sangat indah.**",
        "🌹 **Character": "Ohana Matsumae**",
        "🍁 **Anime": "Hanasaku Iroha**",
        "🍁 **Episode": "Episode 24**",
    },
    {
        "🎁 **Quotes": "Apa kalian menyukai sekolah?Aku sangat menyukainya. Kalian mungkin menganggapnya aneh, tapi sekolah adalah tempat yang hebat.**",
        "🌹 **Character": "Yuki Takeya**",
        "🍁 **Anime": "Gakkou Gurashi!**",
        "🍁 **Episode": "Episode 12**",
    },
    {
        "🎁 **Quotes": "Ada hal yang tak pernah bisa dilihat sebelum melangkah. Karena itu, aku melangkah tanpa rasa takut.**",
        "🌹 **Character": "Itsuki Hashima**",
        "🍁 **Anime": "Imouto sae Ireba Ii.**",
        "🍁 **Episode": "Episode 12**",
    },
    {
        "🎁 **Quotes": "Jangan pernah mati hanya karena hal-hal yang konyol.**",
        "🌹 **Character": "Eris**",
        "🍁 **Anime": "Kono Subarashii Sekai ni Shukufuku wo!: Kono Subarashii Choker ni Shukufuku wo!Kono Subarashii Sekai ni Shukufuku wo! OV**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Ketika bersama denganmu, segalanya jadi menyenangkan.**",
        "🌹 **Character": "Yukiko Asai**",
        "🍁 **Anime": "Nijiiro Days**",
        "🍁 **Episode": "Episode 9**",
    },
    {
        "🎁 **Quotes": "Aku takkan punya kehidupan yang cukup jika hanya mengandalkan keberuntungan saja.**",
        "🌹 **Character": "Shikamaru Nara**",
        "🍁 **Anime": "Naruto Shippuden**",
        "🍁 **Episode": "Episode 16**3",
    },
    {
        "🎁 **Quotes": "Aku tidak mau mengorbankan apapun atau menyeret siapapun hanya untuk menang.**",
        "🌹 **Character": "Makoto Tsukimoto**",
        "🍁 **Anime": "Ping Pong The Animation**",
        "🍁 **Episode": "Episode 2**",
    },
    {
        "🎁 **Quotes": "Tak masalah kalau melarikan diri untuk tetap hidup.Karena kau bukan hewan ternak yang tak punya tempat untuk melarikan diri.**",
        "🌹 **Character": "Kouchou**",
        "🍁 **Anime": "Gin no Saji**",
        "🍁 **Episode": "Episode 11**",
    },
    {
        "🎁 **Quotes": "Sesedih apapun suatu ingatan, setelah diceritakan semuanya hanya akan jadi suatu cerita.**",
        "🌹 **Character": "Ougi Oshino**",
        "🍁 **Anime": "Owarimonogatari**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Jangan buang rasa kesalmu. Karena itu akan jadi bukti kalau kau masih belum menyerah pada dirimu sendiri.**",
        "🌹 **Character": "Ryouma Kurogane**",
        "🍁 **Anime": "Rakudai Kishi no Cavalry**",
        "🍁 **Episode": "Episode 2**",
    },
    {
        "🎁 **Quotes": "Sebagai senior dalam menjalani hidup, (aku) yang berada sedikit didepannya akan menunjukkannya jalan menuju kebahagiaan.**",
        "🌹 **Character": "Koyomi Araragi**",
        "🍁 **Anime": "Owarimonogatari**",
        "🍁 **Episode": "Episode 6**",
    },
    {
        "🎁 **Quotes": "Kita tidak akan bisa berbuat apa-apa jika kita terpisah. (Tapi) ketika seseorang bertemu dengan yang lainnya (semua akan berubah).Sekarang, di suatu tempat mungkin sedang terjadi suatu pertemuan yang dapat mengubah dunia.Mungkin hal itu terjadi di suatu negara yang sangat jauh. Mungkin juga berada di sisi planet ini.Atau mungkin itu berada di klub voli kecil, di sebuah SMA biasa, di sebuah negara kepulauan kecil di timur.Kupikir pertemuan itu terjadi di sini, di Karasuno. Aku tahu aku tak bisa membuktikan apa yang kukatakan, tapi aku sangat yakin. Aku yakin mulai dari sekarang, kalian akan menjadi lebih kuat lagi!**",
        "🌹 **Character": "Ittetsu Takeda**",
        "🍁 **Anime": "Haikyuu!!**",
        "🍁 **Episode": "Episode 7**",
    },
    {
        "🎁 **Quotes": "Datang ke tempatmu sudah cukup untuk menyembuhkan satu hatiku.**",
        "🌹 **Character": "Yuuka Kobayakawa**",
        "🍁 **Anime": "Shoujo-tachi wa Kouya wo Mezasu**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Namaku adalah Nasa Yuzaki, seorang yang lebih cepat dari Nasa, seorang yang akan mencapai kecepatan cahaya.**",
        "🌹 **Character": "Nasa Yuzaki**",
        "🍁 **Anime": "Tonikaku Kawaii**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Orang-orang sering melihat ke langit ketika mereka sedang bingung.**",
        "🌹 **Character": "Tooru Miyamae**",
        "🍁 **Anime": "Seiren**",
        "🍁 **Episode": "Episode 8**",
    },
    {
        "🎁 **Quotes": "Memang benar, akulah yang gila. Aku dibutakan delusi chuunibyou dan terpengaruh rasa keadilan murahan.**",
        "🌹 **Character": "Yuu Ishigami**",
        "🍁 **Anime": "Kaguya-sama wa Kokurasetai?: Tensai-tachi no Renai Zunousen**",
        "🍁 **Episode": "Episode 11**",
    },
    {
        "🎁 **Quotes": "Hanya orang bodoh yang memainkan game yang tak bisa dia menangkan.**",
        "🌹 **Character": "Sora**",
        "🍁 **Anime": "No Game No Life**",
        "🍁 **Episode": "Episode 5**",
    },
    {
        "🎁 **Quotes": "Kau akan membenci dirimu sendiri jika kau melakukan apa yang kau benci.**",
        "🌹 **Character": "Chihiro Sengoku**",
        "🍁 **Anime": "Sakurasou no Pet na Kanojo**",
        "🍁 **Episode": "Episode 19**",
    },
    {
        "🎁 **Quotes": "Aku masih bisa berjuang (sampai sekarang) itu karena kau percaya padaku. Terima kasih Airi, aku bersyukur telah mempercayaimu.**",
        "🌹 **Character": "Satoru Fujinuma**",
        "🍁 **Anime": "Boku dake ga Inai Machi**",
        "🍁 **Episode": "Episode 6**",
    },
    {
        "🎁 **Quotes": "Manusia bisa saling berkumpul, saling membantu, dan menyelesaikan sesuatu. Namun peradaban mereka gampang sekali dimusnahkan oleh para naga. Jadi kurasa naga lebih hebat (dari manusia).**",
        "🌹 **Character": "Tooru**",
        "🍁 **Anime": "Kobayashi-san Chi no Maid Dragon**",
        "🍁 **Episode": "Episode 5**",
    },
    {
        "🎁 **Quotes": "Jangan lari lagi...Jangan pergi ke tempat yang tidak bisa kucapai.Bersamalah denganku selamanya...**",
        "🌹 **Character": "Kouko Kaga**",
        "🍁 **Anime": "Golden Time**",
        "🍁 **Episode": "Episode 6**",
    },
    {
        "🎁 **Quotes": "Dia lebih mencemaskan temannya daripada dirinya sendiri. Dia lebih mementingkan temannya. Aku menghormati perasaannya. Jika kau ingin mencapai sesuatu, kau harus berusaha keras untuk mencapai semuanya.**",
        "🌹 **Character": "Subaru Natsuki**",
        "🍁 **Anime": "Re:Zero kara Hajimeru Isekai Seikatsu**",
        "🍁 **Episode": "Episode 9**",
    },
    {
        "🎁 **Quotes": "Cinta adalah kekonyolan dan tak ada gunanya jika dibandingkan dengan belajar.**",
        "🌹 **Character": "Fuutarou Uesugi**",
        "🍁 **Anime": "Gotoubun no Hanayome**",
        "🍁 **Episode": "Episode 2**",
    },
    {
        "🎁 **Quotes": "Cinta sejati adalah cinta yang tak dipengaruhi oleh penampilan. Jika penampilan orang bisa mempengaruhi perasaanmu, maka cintamu itu palsu.**",
        "🌹 **Character": "Chika Fujiwara**",
        "🍁 **Anime": "Kaguya-sama wa Kokurasetai?: Tensai-tachi no Renai Zunousen**",
        "🍁 **Episode": "Episode 5**",
    },
    {
        "🎁 **Quotes": "Kupikir kalau aku hidup dengan jujur pada diriku sendiri, aku tak akan punya penyesalan. Tapi ternyata itu salah...**",
        "🌹 **Character": "Hime Onizuka**",
        "🍁 **Anime": "Sket Dance**",
        "🍁 **Episode": "Episode 3**",
    },
    {
        "🎁 **Quotes": "Dalam  game, mustahil mengetahui aturan atau tujuan seseorang, karena ada 7 milyar pemain yang bergerak sesuai kenginannya.**",
        "🌹 **Character": "Sora**",
        "🍁 **Anime": "No Game No Life**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Kerinduan mencengkeram orang lebih kuat daripada racun, dan lebih dalam daripada penyakit.**",
        "🌹 **Character": "Lyza**",
        "🍁 **Anime": "Made in Abyss**",
        "🍁 **Episode": "Episode 12**",
    },
    {
        "🎁 **Quotes": "Aku akan terus mengatakannya!Jangan pernah berhenti membuat game, jangan berhenti berkarya.Kau tidak boleh menyerah mengejar impianmu.**",
        "🌹 **Character": "Iori Hashima**",
        "🍁 **Anime": "Saenai Heroine no Sodatekata ♭**",
        "🍁 **Episode": "Episode 10**",
    },
    {
        "🎁 **Quotes": 'Setelah kematian, kalian akan dikirim ke "surga" atau "neraka".**',
        "🌹 **Character": "Decim**",
        "🍁 **Anime": "Death Parade**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Tidur itu sangat penting. Kurang tidur bisa berdampak buruk pada pekerjaan, dan kesehatanmu. Tidur di kursi bisa menghilangkan rasa penatmu untuk sementara, tapi tidak baik untuk punggungmu.**",
        "🌹 **Character": "Umiko Ahagon**",
        "🍁 **Anime": "New Game!!**",
        "🍁 **Episode": "Episode 4**",
    },
    {
        "🎁 **Quotes": "Kadang-kadang pria harus melindungi sesuatu, walaupun dia harus membuang kehormatannya sendiri.**",
        "🌹 **Character": "Kanichi Konishi**",
        "🍁 **Anime": "Shokugeki no Souma**",
        "🍁 **Episode": "Episode 6**",
    },
    {
        "🎁 **Quotes": "Bermuka dua? Aku rasa lebih dari itu. Dia sangat terburu-buru mencari apa yang telah dicuri darinya, lalu dia berhenti menolongku. Malahan dia kepikiran alasan yang tidak masuk akal untuk memonta tolong agar aku tak merasa berhutang kepadanya, meskipun aku adalah orang asing. Siapapun yang hidup seperti itu akhirnya akan menyia-nyiakan seluruh hidupnya!**",
        "🌹 **Character": "Subaru Natsuki**",
        "🍁 **Anime": "Re:Zero kara Hajimeru Isekai Seikatsu**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Kadang-kadang pria harus melindungi sesuatu, walaupun dia harus membuang kehormatannya sendiri.**",
        "🌹 **Character": "Kanichi Konishi**",
        "🍁 **Anime": "Shokugeki no Souma**",
        "🍁 **Episode": "Episode 6**",
    },
    {
        "🎁 **Quotes": "Aku tidak benci bekerja keras. Belajar untuk melakukan sesuatu yang sebelumnya tidak bisa ku lakukan itu bukan hal buruk.**",
        "🌹 **Character": "Subaru Natsuki**",
        "🍁 **Anime": "Re:Zero kara Hajimeru Isekai Seikatsu**",
        "🍁 **Episode": "Episode 4**",
    },
    {
        "🎁 **Quotes": "Mustahil menyelamatkan semua orang. Menyelamatkan banyak orang harus dibayar dengan menghancurkan sebagian kecil orang lainnya.**",
        "🌹 **Character": "Archer**",
        "🍁 **Anime": "Fate/stay night: Unlimited Blade Works 2nd Season**",
        "🍁 **Episode": "Episode 7**",
    },
    {
        "🎁 **Quotes": "Walau dunia ini memusuhimu, aku akan tetap di sampingmu.**",
        "🌹 **Character": "Miyabi Azumaya**",
        "🍁 **Anime": "Dimension W**",
        "🍁 **Episode": "Episode 7**",
    },
    {
        "🎁 **Quotes": "Atasan yang lebih baik, membawa perusahaan lebih baik. Tak ada gunanya mempermasalahkan siapa atasanmu!**",
        "🌹 **Character": "Daikichi Kawachi**",
        "🍁 **Anime": "Usagi Drop**",
        "🍁 **Episode": "Episode 3**",
    },
    {
        "🎁 **Quotes": "Aku percaya kepadamu.**",
        "🌹 **Character": "Raphtalia**",
        "🍁 **Anime": "Tate no Yuusha no Nariagari**",
        "🍁 **Episode": "Episode 4**",
    },
    {
        "🎁 **Quotes": "Ketika ada sesuatu yang populer, itu artinya yang lainnya tidak populer.**",
        "🌹 **Character": "Deishuu Kaiki**",
        "🍁 **Anime": "Koyomimonogatari**",
        "🍁 **Episode": "Episode 5**",
    },
    {
        "🎁 **Quotes": "Orang-orang berkata kalau orang yang meninggal akan pergi ke surga. Tapi menurutku tidak begitu. Aku pikir jika kita mati, kita akan pergi ke hati seseorang. Kita akan tinggal dalam kenangan mereka dan terus hidup. Seperti ayah dan ibu yang tinggal di hati kami. Tapi karena waktu, kenangan pun memudar. Jadi itulah mengapa orang-orang berharap untuk meninggalkan sesuatu agar tidak dilupakan dan tidak pernah dilupakan.**",
        "🌹 **Character": "Kaito Kirishima**",
        "🍁 **Anime": "Ano Natsu de Matteru**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Meski kita hidup dalam peraturan, kita tak bisa menyalamatkan siapapun. Meski aku harus melanggar peraturan, aku takkan membiarkan siapapun menghalangi mimpiku.**",
        "🌹 **Character": "Shirou Kotomine**",
        "🍁 **Anime": "Fate/Apocrypha**",
        "🍁 **Episode": "Episode 12**",
    },
    {
        "🎁 **Quotes": "Lupakan orang yang meninggalkanmu, dan persiapkan dirimu untuk cinta yang baru. Itulah yang harus dilakukan dalam menjalani cinta.**",
        "🌹 **Character": "Kagura**",
        "🍁 **Anime": "Gintama**",
        "🍁 **Episode": "Episode 7**",
    },
    {
        "🎁 **Quotes": "Genos, sejak awal karena keinginan besarku yang ingin menjadi pahlawanlah yang mendorongku untuk berlatih sangat keras.karena itulah aku menjadi sekuat ini.**",
        "🌹 **Character": "Saitama**",
        "🍁 **Anime": "One Punch Man**",
        "🍁 **Episode": "Episode 6**",
    },
    {
        "🎁 **Quotes": "Bukan masalah benci atau tidaknya. Ibuku adalah Ibuku, takkan pernah berubah. Apapun yang terjadi, dialah yang melahirkanku.**",
        "🌹 **Character": "Asuka Tanaka**",
        "🍁 **Anime": "Hibike! Euphonium 2**",
        "🍁 **Episode": "Episode 9**",
    },
    {
        "🎁 **Quotes": "Aku tidak suka hubungan yang tidak jelas.**",
        "🌹 **Character": "Hitagi Senjougahara**",
        "🍁 **Anime": "Bakemonogatari**",
        "🍁 **Episode": "Episode 5**",
    },
    {
        "🎁 **Quotes": "Orang-orang terlalu mengistimewakan sesuatu yang tak bisa dilihat.**",
        "🌹 **Character": "Mahito**",
        "🍁 **Anime": "Jujutsu Kaisen**",
        "🍁 **Episode": "Episode 10**",
    },
    {
        "🎁 **Quotes": "Kita memang menemui jalan buntu, tapi aku takkan berhenti. Demi mereka yang telah tiada, aku harus tetap maju. Sebagai Putri Hyland, sebagai seseorang yang membimbing negri ini menuju keadilan, tolong pinjamkanlah kekuatan kalian.**",
        "🌹 **Character": "Alisha Diphda**",
        "🍁 **Anime": "Tales of Zestiria the X Season 2**",
        "🍁 **Episode": "Episode 3**",
    },
    {
        "🎁 **Quotes": "Melihatnya bekerja keras untuk membenciku, entah mengapa agak menyenangkan.**",
        "🌹 **Character": "Ohana Matsumae**",
        "🍁 **Anime": "Hanasaku Iroha**",
        "🍁 **Episode": "Episode 3**",
    },
    {
        "🎁 **Quotes": "Pasti sangat sulit berusaha melakukan apa yang diinginkan. (Sebenarnya) aku tidak terlalu mengerti, tapi pasti butuh kerja keras untuk mendapatkan hasilnya. Meskipun (kadang) memiliki impian itu membuatmu sulit (menjalani hidup).**",
        "🌹 **Character": "Yuusuke Fujisaki**",
        "🍁 **Anime": "Sket Dance**",
        "🍁 **Episode": "Episode 42**",
    },
    {
        "🎁 **Quotes": "Entah itu orang suci ataupun pendosa, semua orang punya hak untuk menegakkan keadilan mereka. Menolak keadilan mereka dan membunuhnya adalah hal tabu bagiku.**",
        "🌹 **Character": "Brad Blackstone**",
        "🍁 **Anime": "Taboo Tattoo**",
        "🍁 **Episode": "Episode 9**",
    },
    {
        "🎁 **Quotes": "Kemenangan sejati bukanlah saat kau menang melawan yang kuat.Melainkan saat kau berhasil melindungi sesuatu yang berharga bagimu.**",
        "🌹 **Character": "Duy Might**",
        "🍁 **Anime": "Naruto Shippuden**",
        "🍁 **Episode": "Episode 41**9",
    },
    {
        "🎁 **Quotes": "Setiap jomblo yang punya hewan peliharaan pasti merasakan kebahagiaan palsu**",
        "🌹 **Character": "Mayumi Nishikino**",
        "🍁 **Anime": "Bokura wa Minna Kawaisou**",
        "🍁 **Episode": "Episode 11**",
    },
    {
        "🎁 **Quotes": "Kau adalah seorang profesional, tapi jika kau tak bisa menyeimbangkan antara pembunuh (profesi) dan guru (tuntutan peran dalam profesi), maka ini (sekolah) adalah tempat terburuk bagi orang profesional sepertimu.**",
        "🌹 **Character": "Tadaomi Karasuma**",
        "🍁 **Anime": "Ansatsu Kyoushitsu**",
        "🍁 **Episode": "Episode 4**",
    },
    {
        "🎁 **Quotes": "Aku tahu jika kau sedang berbohong. Aku tahu kalau kau juga tak bisa mengatakan alasannya. Jadi, kau tak perlu meyakinkanku, menutupi semuanya dengan kebohongan, atau menyalahkan dirimu sendiri seperti itu. Karena aku percaya padamu.**",
        "🌹 **Character": "Rem**",
        "🍁 **Anime": "Re:Zero kara Hajimeru Isekai Seikatsu**",
        "🍁 **Episode": "Episode 19**",
    },
    {
        "🎁 **Quotes": "Semua bergantung pada tampan atau tidaknya seseorang. Itulah pedoman hidupku. Jika tidak tampan, berarti bukan laki-laki.**",
        "🌹 **Character": "Masamune Makabe**",
        "🍁 **Anime": "Masamune-kun no Revenge**",
        "🍁 **Episode": "Episode 1**",
    },
    {
        "🎁 **Quotes": "Entah itu jalan yang lurus ataupun jalan yang menyesatkan, selama kami masih bisa berjalan di sampingmu, kami tak peduli ke manapun kami pergi.**",
        "🌹 **Character": "Toushirou Hijikata**",
        "🍁 **Anime": "Gintama°**",
        "🍁 **Episode": "Episode 48**",
    },
    {
        "🎁 **Quotes": "Kau harus punya mata dan keberanian untuk mengatakan yang bagus ya bagus, dan jelek ya jelek.**",
        "🌹 **Character": "Utaha Kasumigaoka**",
        "🍁 **Anime": "Saenai Heroine no Sodatekata ♭**",
        "🍁 **Episode": "Episode 2**",
    },
    {
        "🎁 **Quotes": "Memang benar kalau aku putus asa dengan dunia nyata. Tapi aku tidak putus asa dengan diriku sendiri. Yang memutuskan apakah hidupku membosankan, menyenangkan atau biasa-biasa saja bukalah dunia ini, tapi diriku sendiri. Selama aku memiliki kemauan, tak ada yang mustahil. Kau pun juga bisa melakukan apapun yang kau inginkan.**",
        "🌹 **Character": "Keima Katsuragi**",
        "🍁 **Anime": "Kami nomi zo Shiru Sekai II**",
        "🍁 **Episode": "Episode 7**",
    },
    {
        "🎁 **Quotes": "Sejak kecil, aku selalu membayangkan pemandangan indah yang ada di mana-mana. Pemandangan yang selalu aku lihat dan tak terhitung dalam mimpiku. Tapi aku belum pernah kesana. Mereka mengatakan itu adalah efek samping dari Antifeminas milik Inglobe yang ada pada diriku. Tapi aku tak peduli dengan penyebab itu, Aku hanya ingin mencari sesuatu. Karena itu aku melakukan perjalanan.**",
        "🌹 **Character": "Ichika Takatsuki**",
        "🍁 **Anime": "Ano Natsu de Matteru**",
        "🍁 **Episode": "Episode 2**",
    },
    {
        "🎁 **Quotes": "Bagi yang berusaha maka Tuhan akan tersenyum padamu, itu adalah bohong.Tapi, takdir Tuhan akan berkedip padamu.**",
        "🌹 **Character": "Kumiko Oumae**",
        "🍁 **Anime": "Hibike! Euphonium**",
        "🍁 **Episode": "Episode 12**",
    },
    {
        "🎁 **Quotes": "Perempuan yang sedang jatuh cinta bisa menentang Tuhan.**",
        "🌹 **Character": "Tsushima**",
        "🍁 **Anime": "Toaru Majutsu no Index III**",
        "🍁 **Episode": "Episode 8**",
    },
    {
        "🎁 **Quotes": "Aku tidak bisa fokus karena terpana olehmu.**",
        "🌹 **Character": "Fuutarou Uesugi**",
        "🍁 **Anime": "Gotoubun no Hanayome**",
        "🍁 **Episode": "Episode 10**",
    },
    {
        "🎁 **Quotes": "Seekor ikan, baik yang tinggal di air jernih atau kotor, selama ikan itu terus berenang ke depan, dia akan tumbuh dengan indah.**",
        "🌹 **Character": "Koro-sensei**",
        "🍁 **Anime": "Ansatsu Kyoushitsu**",
        "🍁 **Episode": "Episode 7**",
    },
    {
        "🎁 **Quotes": "Wanita itu orang yang realistis. Kami tidak percaya hanya pada kata-kata.**",
        "🌹 **Character": "Aiza Nagi**",
        "🍁 **Anime": "Shigatsu wa Kimi no Uso**",
        "🍁 **Episode": "Episode 17**",
    },
    {
        "🎁 **Quotes": "Tidak ada kebahagiaan yang begitu berat hingga membuatmu hancur. Kebahagiaan itu bukanlah (suatu hal yang) berat maupun ringan. Jangan berlebihan menganggap kebahagiaan. Semua jenis kebahagiaan akan cocok untukmu. Jadi jangan membenci kebahagiaan seperti itu. Jangan membenci dunia, jangan membenci semua hal. Jangan membenci dirimu sendiri. Semua jenis kebencian di dalam dirimu semuanya akan kuterima dan kutanggung untukmu. Aku ingin kau lebih mencintai dirimu sendiri.**",
        "🌹 **Character": "Koyomi Araragi**",
        "🍁 **Anime": "Owarimonogatari**",
        "🍁 **Episode": "Episode 5**",
    },
]

PUBG = [
    "🏆 **Tempat Favoritku untuk berkendara adalah Miramar**",
    "🏆 **Aku tidak pernah menyukai chicken, tapi tidak dengan chicken di PUBG**",
    "🏆 **Tetap tenang dan dapatkan chicken dinner**",
    "🏆 **Belum saatnya tidur hingga chicken dinner**",
    "🏆 **Tidak ada kemenangan sejati tanpa chicken dinner**",
    "🏆 **Bermain PUBG tidak melulu bareng kawan. Justru main random bisa ningkatin skill-mu**",
    "🏆 **Daripada memainkan hati seseorang, Lebih baik kita memainkan game PUBG**",
    "🏆 **Legenda PUBG selalu bermain lewat tengah malam**",
    "🏆 **Kami adalah Gamers PUBG. Tidak butuh beautiful, hanya butuh battery full**",
    "🏆 **Hidupku seakan berada di dalam PUBG. Aku sedang berada di red zone?**",
    "🏆 **Bermain solo vs squad hanya untuk melatih skill setelah lama off**",
    "🏆 **Semoga senantiasa panjang umur buat teman yang kalau diajak join mabar langsung login**",
    "🏆 **Sultan boleh, No Skill jangan**",
    "🏆 **Kami bukanlah player nob, kami hanya baru mulai**",
    "🏆 **Tidak peduli turun di Erangel, Vikendi, Sanhok, ataupun Miramar. Asal usaha, Chicken pasti bisa**",
    "🏆 **Cintailah Free Fire-mu, tanpa perlu menghina PUBG-ku**",
    "🏆 **Cukup 15 menit untuk pertempuran karena kami tahu waktu adalah uang**",
    "🏆 **Kalau ada yang nanya kenapa nggak malem mingguan? Bilang kalau lagi ngepush rank**",
    "🏆 **Saat sepi, hanya game PUBG yang bisa membuatku happy**",
    "🏆 **Skill dewa yang sebenarnya adalah yang membunuh lawan tanpa berperang**",
    "🏆 **Berpikir seperti sebuah gelas yang selalu kosong, maka dunia ini akan sangat terbuka bagimu**",
    "🏆 **Di dalam game PUBG kita diajarkan untuk tidak terus menerus berperang. Tapi bagaimana kita bertarung dan menjaga kawan untuk mendapatkan Winner Winner Chicken Dinner**",
    "🏆 **Jika kamu tidak bertekad mendapatkan chicken dinner malam ini, kamu tidak akan pernah mendapatkannya**",
    "🏆 **Bermain PUBG hanya untuk menghibur diri dari dunia yang sungguh melelahkan**",
    "🏆 **Kami mabar tidak untuk membuang-buang waktu, karena inilah cara kami untuk menjaga tali silaturahmi**",
    "🏆 **Kami tidak memainkan permainan yang mudah ditentukan menang atau kalahnya. Karena kemenangan itu akan terasa manis saat ada tantangannya**",
    "🏆 **PUBG tidak hanya sekedar game. Dibutuhkan skill dan kecepatan berpikir untuk segera bertindak**",
    "🏆 **Di dalam game PUBG mengajarkan, jika kita menemukan lawan yang menghadang, kita telah berada dijalur yang benar**",
    "🏆 **Jangan takut memulai pertempuran karna mereka PRO. Dulunya mereka juga hanya seorang pemula**",
    "🏆 **Kita tidak dilahirkan sebagai pemenang. Kita harus meraihnya sendiri dengan usaha dan kerja keras**",
    "🏆 **Semua orang berhak untuk chicken dinner, tapi tidak semua orang punya kemampuan untuk meraihnya**",
    "🏆 **Jangan bermain untuk memenangkan pertempuran, tapi bermain lah untuk kesenangan**",
    "🏆 **Izinkan aku mencintaimu tanpa harus menghapus PUBG ku**",
    "🏆 **Aku rela turun rank demi ngajarin kamu main PUBG. Karena perlu kamu tahu, main game lebih menyenangkan dari main perasaan**",
    "🏆 **Belajar dari game PUBG. Bukan tentang siapa yang datang duluan, tapi siapa yang bertahan sampai akhir**",
    "🏆 **Prajurit sejati bertempur bukan karena dia membenci musuh di depannya. Tapi karena dia mencintai apa yang ada dibelakangnya**",
    "🏆 **Aku menembak di PUBG aja belum tentu On Target, apalagi nembak kamu. Pasti Mission Failed**",
    "🏆 **Bilang ke dilan. Yang berat itu bukan rindu, tapi solo versus squad**",
    "🏆 **Mengendalikan AIM-ku sama susahnya seperti Move On darimu**",
    "🏆 **Lari mengejar airdrop saja aku mau, apa lagi lari mengejar cintamu**",
    "🏆 **Pacaran sama pemain PUBG itu gampang. Lagi nggak ngedate, push rank pun jadi**",
    "🏆 **Bukannya tak ingin membalas chat darimu,. Tapi mengertilah kalau game PUBG tidak ada opsi pause**",
    "🏆 **Kamu seperti Airdrop yang ingin aku raih, tapi banyak juga yang mendambakanmu**",
    "🏆 **Aku memang tidak seperti P18C yang siaga menjagamu dari dekat. Tapi biarkan aku menjadi seperti AWM yang siap menjagamu dari jauh**",
    "🏆 **Carilah pasangan yang kalau lagi main PUBG larinya ke safe zone, bukan red zone**",
    "🏆 **Kami tidak ingin to be a girl’s heart winner. Kami hanya ingin get a chicken dinner**",
    "🏆 **Kenapa gua suka main PUBG? Karena Cuma di PUBG nembak tidak pernah ditolak**",
    "🏆 **Mana yang lebih menyakitkan: Pacar yang tiba-tiba minta putus, atau AWM yang tembus helm level 3?**",
    "🏆 **Kerjasama membuat chicken dinner menjadi nyata**",
    "🏆 **Ada dua poin utama untuk merebut chicken dinner, skill dan kerja sama. Skill bisa diusahakan, tapi kerja sama sulit dibentuk**",
    "🏆 **Pelajaran yang didapatkan dari bermain PUBG adalah: bahwa kemenangan membutuhkan kerjasama, keegoisan individu akan membawa pada kekalahan**",
    "🏆 **Sebuah tim dibentuk untuk mencapai tujuan yang sama – Chicken dinner**",
    "🏆 **Seorang pemenang selalu berpikir tentang kerjasama. Seorang pecundang selalu berpikir tentang berkuasa**",
    "🏆 **Bukan hanya tentang game. PUBG juga mengajarkan bagaimana kita harus melindungi kawan dan berjuang bersama**",
    "🏆 **Dari PUBG aku belajar bahwa aku harus memusnahkan musuh-musuhku. Namun disisi lain, aku belajar untuk melindungi teman-temanku**",
    "🏆 **Skill individu boleh mumpuni. Tapi tanpa Kerja sama, tidak akan mencapai apa-apa**",
]

HECKER = [
    "🃏 **Apa yang dilakukan peretas adalah mencari tahu teknologi dan bereksperimen dengannya dengan cara yang tidak pernah dibayangkan banyak orang. Mereka juga memiliki keinginan yang kuat untuk membagikan informasi ini dengan orang lain dan menjelaskannya kepada orang-orang yang satu-satunya kualifikasi mungkin adalah keinginan untuk belajar.**",
    "🃏 **Peretas adalah bakat. Anda tidak akan mempelajarinya di sekolah. Ini seperti menjadi Messi atau C. Ronaldo. Jika Anda dilahirkan untuk menjadi seorang peretas, itu adalah takdir Anda. Jika tidak, Anda akan diretas.**",
    "🃏 **Kebodohan manusia, itulah sebabnya peretas selalu menang.**",
    "🃏 **Ingat, ketika Anda terhubung dengan komputer lain, Anda terhubung ke setiap komputer yang terhubung dengan komputer.**",
    "🃏 **Peretasan komputer seperti ikatan kimia yang mengikat kita semua.**",
    "🃏 **Jika Anda adalah peretas yang baik, semua orang mengenal Anda. Tetapi, jika Anda peretas yang hebat tidak ada yang mengenal Anda.**",
    "🃏 **Sains adalah apa yang kami pahami dengan cukup baik untuk dijelaskan ke komputer; seni adalah segalanya.**",
    "🃏 **Anda tidak dapat meretas takdir, kekuatan kasar... Anda perlu pintu belakang, saluran samping ke dalam hidup.**",
    "🃏 **Lawan dulu dan sekarang memiliki kelemahan esensial yang sama tentang mereka. Pertama mereka ingin menggunakan Anda, kemudian ingin menjadi Anda, kemudian mereka ingin menghabisi Anda.**",
    "🃏 **Bagi saya, komputer itu alat yang paling luar biasa yang pernah kita miliki. Ini setara dengan sepeda untuk pikiran kita.**",
    "🃏 **Tidak ada yang tidak baik atau buruk tentang pengetahuan itu sendiri; moralitas terletak pada penerapan pengetahuan.**",
    "🃏 **Saya percaya pada dunia di mana semua hal ini bisa terjadi, bahkan jika saya harus melakukannya sendiri.**",
    "🃏 **Pelajari hari Ini, terapkan hari Ini.**",
    "🃏 **Hal terpenting tentang teknologi adalah bagaimana hal itu mengubah orang.**",
    "🃏 **Percayalah pada getaran yang Anda dapatkan, energi tidak berbohong.**",
    "🃏 **Anda hanya berjarak satu klik untuk menemukan diri sejati anda.**",
    "🃏 **Ketika kita semua memiliki akses ke informasi, kita kuat. Ketika kita kuat, kita tetap memiliki kekuatan untuk melakukan hal yang mustahil.**",
    "🃏 **Saat berjudi, seseorang harus tahu lawan mereka, dan kelemahan mereka. Terutama, jika lawan itu adalah mesin.**",
    "🃏 **Kami melakukan hal-hal yang kami lakukan untuk rakyat, bukan untuk kepentingan kita sendiri seperti sebuah ketenaran.**",
    "🃏 **Virality is not an accident. It is engineered. And that's why growth hackers beat traditional marketers.**",
    "🃏 **Jika Anda yakin bahwa satu ide dapat mengubah dunia, maka kami percaya Anda adalah gagasan itu.**",
    "🃏 **Pemerintah dunia tidak bisa terus menerus menekan Anonymous untuk selamanya, karena jumlah mereka terus berkembang setiap hari.**",
    "🃏 **Duniaku jauh lebih menarik dari dunia mereka.**",
    "🃏 **Ini tak semudah yang orang lain lihat, dan ini bukan hal yang dapat dilakukan semua orang.**",
    "🃏 **Tak ada yang tahu identitas kami.**",
    "🃏 **Kami tumbuh untuk percaya bahwa kami tidak bersalah sampai terbukti bersalah, tapi kenyataannya kami selalu divonis bersalah.**",
    "🃏 **Di balik layar monitor ini aku dapat melihat dunia.**",
    "🃏 **Kami dimulai sebagai sekelompok orang yang dikendalikan tanpa sebuah alasan.**",
    "🃏 **Bukan tanpa alasan hal ini kami lakukan, ini semua untuk kebebasan yang dikekang pemerintah.**",
    "🃏 **Kita tidak perlu pemimpin. Kita punya ide. Ide adalah anti peluru.**",
    "🃏 **Faktanya ya, mereka sangat mudah. Masalahnya adalah anda tidak harus melindungi diri dari orang bodoh. Anda harus melindungi diri terhadap orang seperti saya.**",
    "🃏 **Ketika penjahat kaya membutuhkan orang miskin, orang miskin mungkin membuat harga yang mereka mau.**",
    "🃏 **Lawan dulu dan sekarang memiliki kelemahan esensial yang sama tentang mereka. Pertama mereka ingin menggunakan anda, kemudian ingin menjadi anda, kemudian mereka ingin menghabisi anda.**",
    "🃏 **Bukan monster yang harus kita takuti; itu adalah orang-orang yang tidak mengenali monster yang sama di dalam diri mereka.**",
    "🃏 **Jika anda adalah peretas yang baik, semua orang mengenal anda. Tetapi, jika anda peretas yang hebat tidak ada yang mengenal anda.**",
    "🃏 **Mereka menganggapku remeh dalam dunia nyata, tapi mereka tidak tahu aku di dalam 'Cyber World'.**",
    "🃏 **Kami dimulai sebagai sekelompok orang yang dikendalikan tanpa sebuah alasan.**",
    "🃏 **Menjadi seorang kriminal bukanlah hal yang memalukan. Sedangkan untuk tetap menjadi penjahat adalah aib.**",
    "🃏 **Bukan tanpa alasan hal ini kami lakukan, ini semua untuk kebebasan yang dikekang pemerintah.**",
    "🃏 **Kami tumbuh untuk percaya bahwa kami tidak bersalah sampai terbukti bersalah, tapi kenyataannya kami selalu divonis bersalah.**",
    "🃏 **Kebanyakan peretas masih muda, karena orang cenderung mudah beradaptasi. Selama anda tetap bisa beradaptasi, anda selalu bisa menjadi peretas yang baik.**",
    "🃏 **Jika anda yakin bahwa satu ide dapat mengubah dunia, maka kami percaya anda adalah gagasan itu.**",
    "🃏 **Kemajuan teknologi seperti kapak di tangan seorang penjahat patologis.**",
    "🃏 **I'm a hacker, but I'm the good kind of hackers. And I've never been a criminal.**",
    "🃏 **If you wanna know how not secure you are, just take a look around. Nothing's secure. Nothing's safe. I don't hate technology, I don't hate hackers, because that's just what comes with it, without those hackers we wouldn't solve the problems we need to solve, especially security.**",
    "🃏 **Social engineering has become about 75% of an average hacker's toolkit, and for the most successful hackers, it reaches 90% or more.**",
    "🃏 **Hackers are breaking the systems for profit. Before, it was about intellectual curiosity and pursuit of knowledge and thrill, and now hacking is big business.**",
    "🃏 **Very smart people are often tricked by hackers, by phishing. I don't exclude myself from that. It's about being smarter than a hacker. Not about being smart.**",
    "🃏 **Hackers rarely have full knowledge of the technology stack of a target.**",
    "🃏 **Hackers are seen as shadowy figures with superhuman powers that threaten civilization.**",
    "🃏 **What fashion has started from hackers? They have bad posture, and they don't go out. I wish I had a hacker boyfriend - they stay at home up in the bedroom.**",
    "🃏 **Garbage can provide important details for hackers: names, telephone numbers, a company's internal jargon.**",
    "🃏 **When hackers have access to powerful computers that use brute force hacking, they can crack almost any password; even one user with insecure access being successfully hacked can result in a major breach.**",
    "🃏 **In the aftermath of the oh-so-predictable crash, the Bitcoin fanatics have begun marshaling out excuse after excuse for why this non-investment investment lost so much of its value so fast. One was that hackers attacked some of the exchanges for Bitcoins and crippled it. Really? A hacker can wreck an entire market?**",
    "🃏 **Hackers often describe what they do as playfully creative problem solving. Heather Brooke Problem Creative Often Computer hackers do not need to know each other's real names, or even live on the same continent, to steal millions in mere hours.**",
    "🃏 **We face cyber threats from state-sponsored hackers, hackers for hire, global cyber syndicates, and terrorists. They seek our state secrets, our trade secrets, our technology, and our ideas - things of incredible value to all of us. They seek to strike our critical infrastructure and to harm our economy.**",
    "🃏 **Hackers are becoming more sophisticated in conjuring up new ways to hijack your system by exploiting technical vulnerabilities or human nature. Don't become the next victim of unscrupulous cyberspace intruders.**",
    "🃏 **I don't hate technology, I don't hate hackers, because that's just what comes with it, without those hackers we wouldn't solve the problems we need to solve, especially security.**",
    "🃏 **I really didn't understand why hackers would want to hack into a classroom. Are they going to learn algebra? Maybe calculus?**",
]

BUCIN = [
    "Gak salah kalo aku lebih berharap sama orang yang lebih pasti tanpa khianati janji-janji",
    "Kalau aku memang tidak sayang sama kamu ngapain aku mikirin kamu. Tapi semuanya kamu yang ngganggap aku gak sayang sama kamu",
    "Jangan iri dan sedih jika kamu tidak memiliki kemampuan seperti yang orang miliki. Yakinlah orang lain juga tidak memiliki kemampuan sepertimu",
    "Hanya kamu yang bisa membuat langkahku terhenti, sambil berkata dalam hati mana bisa aku meninggalkanmu",
    "Tetap tersenyum walaluku masih dibuat menunggu dan rindu olehmu, tapi itu demi kamu",
    "Tak semudah itu melupakanmu",
    "Secuek-cueknya kamu ke aku, aku tetap sayang sama kamu karena kamu telah menerima aku apa adanya",
    "Aku sangat bahagia jika kamu bahagia didekatku, bukan didekatnya",
    "Jadilah diri sendiri, jangan mengikuti orang lain, tetapi tidak sanggup untuk menjalaninya",
    "Cobalah terdiam sejenak untuk memikirkan bagaimana caranya agar kita dapat menyelesaikan masalah ini bersama-sama",
    "Bisakah kita tidak bermusuhan setelah berpisah, aku mau kita seperti dulu sebelum kita jadian yang seru-seruan bareng, bercanda dan yang lainnya",
    "Aku ingin kamu bisa langgeng sama aku dan yang aku harapkan kamu bisa jadi jodohku",
    "Cinta tak bisa dijelaskan dengan kata-kata saja, karena cinta hanya mampu dirasakan oleh hati",
    "Masalah terbesar dalam diri seseorang adalah tak sanggup melawan rasa takutnya",
    "Selamat pagi buat orang yang aku sayang dan orang yang membenciku, semoga hari ini hari yang lebih baik daripada hari kemarin buat aku dan kamu",
    "Jangan menyerah dengan keadaanmu sekarang, optimis karena optimislah yang bikin kita kuat",
    "Kepada pria yang selalu ada di doaku aku mencintaimu dengan tulus apa adanya",
    "Tolong jangan pergi saat aku sudah sangat sayang padamu",
    "Coba kamu yang berada diposisiku, lalu kamu ditinggalin gitu aja sama orang yang lo sayang banget",
    "Aku takut kamu kenapa-napa, aku panik jika kamu sakit, itu karena aku cinta dan sayang padamu",
    "Sakit itu ketika cinta yang aku beri tidak kamu hargai",
    "Kamu tiba-tiba berubah tanpa sebab tapi jika memang ada sebabnya kamu berubah tolong katakan biar saya perbaiki kesalahan itu",
    "Karenamu aku jadi tau cinta yang sesungguhnya",
    "Senyum manismu sangatlah indah, jadi janganlah sampai kamu bersedih",
    "Berawal dari kenalan, bercanda bareng, ejek-ejekan kemudian berubah menjadi suka, nyaman dan akhirnya saling sayang dan mencintai",
    "Tersenyumlah pada orang yang telah menyakitimu agar sia tau arti kesabaran yang luar biasa",
    "Aku akan ingat kenangan pahit itu dan aku akan jadikan pelajaran untuk masa depan yang manis",
    "Kalau memang tak sanggup menepati janjimu itu setidaknya kamu ingat dan usahakan jagan membiarkan janjimu itu sampai kau lupa",
    "Hanya bisa diam dan berfikir Kenapa orang yang setia dan baik ditinggalin yang nakal dikejar-kejar giliran ditinggalin bilangnya laki-laki itu semuanya sama",
    "Walaupun hanya sesaat saja kau membahagiakanku tapi rasa bahagia yang dia tidak cepat dilupakan",
    "Aku tak menyangka kamu pergi dan melupakan ku begitu cepat",
    "Jomblo gak usah diam rumah mumpung malam minggu ya keluar jalan lah kan jomblo bebas bisa dekat sama siapapun pacar orang mantan sahabat bahkan sendiri atau bareng setan pun bisa",
    "Kamu adalah teman yang selalu di sampingku dalam keadaan senang maupun susah Terimakasih kamu selalu ada di sampingku",
    "Aku tak tahu sebenarnya di dalam hatimu itu ada aku atau dia",
    "Tak mudah melupakanmu karena aku sangat mencintaimu meskipun engkau telah menyakiti aku berkali-kali",
    "Hidup ini hanya sebentar jadi lepaskan saja mereka yang menyakitimu Sayangi Mereka yang peduli padamu dan perjuangan mereka yang berarti bagimu",
    "Tolong jangan pergi meninggalkanku aku masih sangat mencintai dan menyayangimu",
    "Saya mencintaimu dan menyayangimu jadi tolong jangan engkau pergi dan meninggalkan ku sendiri",
    "Saya sudah cukup tahu bagaimana sifatmu itu kamu hanya dapat memberikan harapan palsu kepadaku",
    "Aku berusaha mendapatkan cinta darimu tetapi Kamunya nggak peka",
    "Aku bangkit dari jatuh ku setelah kau jatuhkan aku dan aku akan memulainya lagi dari awal Tanpamu",
    "Mungkin sekarang jodohku masih jauh dan belum bisa aku dapat tapi aku yakin jodoh itu Takkan kemana-mana dan akan ku dapatkan",
    "Datang aja dulu baru menghina orang lain kalau memang dirimu dan lebih baik dari yang kau hina",
    "Membelakanginya mungkin lebih baik daripada melihatnya selingkuh didepan mata sendiri",
    "Bisakah hatimu seperti angsa yang hanya setia pada satu orang saja",
    "Aku berdiri disini sendiri menunggu kehadiran dirimu",
    "Aku hanya tersenyum padamu setelah kau menyakitiku agar kamu tahu arti kesabaran",
    "Maaf aku lupa ternyata aku bukan siapa-siapa",
    "Untuk memegang janjimu itu harus ada buktinya jangan sampai hanya janji palsu",
    "Aku tidak bisa selamanya menunggu dan kini aku menjadi ragu Apakah kamu masih mencintaiku",
    "Jangan buat aku terlalu berharap jika kamu tidak menginginkanku",
    "Lebih baik sendiri daripada berdua tapi tanpa kepastian",
    "Pergi bukan berarti berhenti mencintai tapi kecewa dan lelah karena harus berjuang sendiri",
    "Bukannya aku tidak ingin menjadi pacarmu Aku hanya ingin dipersatukan dengan cara yang benar",
    "Akan ada saatnya kok aku akan benar-benar lupa dan tidak memikirkan mu lagi",
    "Kenapa harus jatuh cinta kepada orang yang tak bisa dimiliki",
    "Jujur aku juga memiliki perasaan terhadapmu dan tidak bisa menolakmu tapi aku juga takut untuk mencintaimu",
    "Maafkan aku sayang tidak bisa menjadi seperti yang kamu mau",
    "Jangan memberi perhatian lebih seperti itu cukup biasa saja tanpa perlu menimbulkan rasa",
    "Aku bukan mencari yang sempurna tapi yang terbaik untukku",
    "Sendiri itu tenang tidak ada pertengkaran kebohongan dan banyak aturan",
    "Cewek strong itu adalah yang sabar dan tetap tersenyum meskipun dalam keadaan terluka",
    "Terima kasih karena kamu aku menjadi lupa tentang masa laluku",
    "Cerita cinta indah tanpa masalah itu hanya di dunia dongeng saja",
    "Kamu tidak akan menemukan apa-apa di masa lalu Yang ada hanyalah penyesalan dan sakit hati",
    "Mikirin orang yang gak pernah mikirin kita itu emang bikin gila",
    "Dari sekian lama menunggu apa yang sudah didapat",
    "Perasaan Bodo gue adalah bisa jatuh cinta sama orang yang sama meski udah disakiti berkali-kali",
    "Yang sendiri adalah yang bersabar menunggu pasangan sejatinya",
    "Aku terlahir sederhana dan ditinggal sudah biasa",
    "Aku sayang kamu tapi aku masih takut untuk mencintaimu",
    "Bisa berbagi suka dan duka bersamamu itu sudah membuatku bahagia",
    "Aku tidak pernah berpikir kamu akan menjadi yang sementara",
    "Jodoh itu bukan seberapa dekat kamu dengannya tapi seberapa yakin kamu dengan Allah",
    "Jangan paksa aku menjadi cewek seperti seleramu",
    "Hanya yang sabar yang mampu melewati semua kekecewaan",
    "Balikan sama kamu itu sama saja bunuh diri dan melukai perasaan ku sendiri",
    "Tak perlu membalas dengan menyakiti biar Karma yang akan urus semua itu",
    "Aku masih ingat kamu tapi perasaanku sudah tidak sakit seperti dulu",
]
