from _typeshed import Incomplete
from firebase_admin import exceptions as exceptions

def handle_platform_error_from_googleapiclient(error, handle_func: Incomplete | None = None): ...
def handle_googleapiclient_error(error, message: Incomplete | None = None, code: Incomplete | None = None, http_response: Incomplete | None = None): ...
