import google.auth
from _typeshed import Incomplete
from firebase_admin import exceptions as exceptions

def get_metrics_header(): ...
def get_app_service(app, name, initializer): ...
def handle_platform_error_from_requests(error, handle_func: Incomplete | None = None): ...
def handle_operation_error(error): ...
def handle_requests_error(error, message: Incomplete | None = None, code: Incomplete | None = None): ...

class EmulatorAdminCredentials(google.auth.credentials.Credentials):
    token: str
    def __init__(self) -> None: ...
    def refresh(self, request) -> None: ...
