from _typeshed import Incomplete

def delete_instance_id(instance_id, app: Incomplete | None = None) -> None: ...

class _InstanceIdService:
    error_codes: Incomplete
    def __init__(self, app) -> None: ...
    def delete_instance_id(self, instance_id) -> None: ...
