# coding: utf-8

"""
Wrk API v1

Wrk Platform Public API V1

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from wrk_platform_sdk.models.wrkflow_schedule import WrkflowSchedule


class TestWrkflowSchedule(unittest.TestCase):
    """WrkflowSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WrkflowSchedule:
        """Test WrkflowSchedule
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WrkflowSchedule`
        """
        model = WrkflowSchedule()
        if include_optional:
            return WrkflowSchedule(
                description = '',
                schedule = ''
            )
        else:
            return WrkflowSchedule(
        )
        """

    def testWrkflowSchedule(self):
        """Test WrkflowSchedule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
