# Generated by Django 5.1.5 on 2025-02-06 02:12

import django.db.models.deletion
import jestit.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authit', '0004_alter_user_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='authit.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='authit.user')),
            ],
            bases=(models.Model, jestit.models.base.JestitBase),
        ),
    ]
