# coding: utf-8

"""
    Trackside Software TeamDB API v2.0

    This API enables you to access TeamDB data  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: support@trackside.fr
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ParameterCrossTable(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'from_parameter_path': 'str',
        'to_parameter_path': 'str'
    }

    attribute_map = {
        'from_parameter_path': 'FromParameterPath',
        'to_parameter_path': 'ToParameterPath'
    }

    def __init__(self, from_parameter_path=None, to_parameter_path=None):  # noqa: E501
        """ParameterCrossTable - a model defined in Swagger"""  # noqa: E501
        self._from_parameter_path = None
        self._to_parameter_path = None
        self.discriminator = None
        self.from_parameter_path = from_parameter_path
        self.to_parameter_path = to_parameter_path

    @property
    def from_parameter_path(self):
        """Gets the from_parameter_path of this ParameterCrossTable.  # noqa: E501

        The full parameter path which belongs to the From version  The path must be described only by / or \\\\\\\\.  # noqa: E501

        :return: The from_parameter_path of this ParameterCrossTable.  # noqa: E501
        :rtype: str
        """
        return self._from_parameter_path

    @from_parameter_path.setter
    def from_parameter_path(self, from_parameter_path):
        """Sets the from_parameter_path of this ParameterCrossTable.

        The full parameter path which belongs to the From version  The path must be described only by / or \\\\\\\\.  # noqa: E501

        :param from_parameter_path: The from_parameter_path of this ParameterCrossTable.  # noqa: E501
        :type: str
        """
        if from_parameter_path is None:
            raise ValueError("Invalid value for `from_parameter_path`, must not be `None`")  # noqa: E501

        self._from_parameter_path = from_parameter_path

    @property
    def to_parameter_path(self):
        """Gets the to_parameter_path of this ParameterCrossTable.  # noqa: E501

        The full parameter path which belongs to the To version  The path must be described only by / or \\\\\\\\.  # noqa: E501

        :return: The to_parameter_path of this ParameterCrossTable.  # noqa: E501
        :rtype: str
        """
        return self._to_parameter_path

    @to_parameter_path.setter
    def to_parameter_path(self, to_parameter_path):
        """Sets the to_parameter_path of this ParameterCrossTable.

        The full parameter path which belongs to the To version  The path must be described only by / or \\\\\\\\.  # noqa: E501

        :param to_parameter_path: The to_parameter_path of this ParameterCrossTable.  # noqa: E501
        :type: str
        """
        if to_parameter_path is None:
            raise ValueError("Invalid value for `to_parameter_path`, must not be `None`")  # noqa: E501

        self._to_parameter_path = to_parameter_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ParameterCrossTable, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ParameterCrossTable):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
