from _typeshed import Incomplete
from firebase_admin import credentials as credentials
from firebase_admin.__about__ import __version__ as __version__

def initialize_app(credential: Incomplete | None = None, options: Incomplete | None = None, name=...): ...
def delete_app(app) -> None: ...
def get_app(name=...): ...

class _AppOptions:
    def __init__(self, options) -> None: ...
    def get(self, key, default: Incomplete | None = None): ...

class App:
    def __init__(self, name, credential, options) -> None: ...
    @property
    def name(self): ...
    @property
    def credential(self): ...
    @property
    def options(self): ...
    @property
    def project_id(self): ...
