from _typeshed import Incomplete

class Client:
    emulated: bool
    def __init__(self, app, tenant_id: Incomplete | None = None) -> None: ...
    @property
    def tenant_id(self): ...
    def create_custom_token(self, uid, developer_claims: Incomplete | None = None): ...
    def verify_id_token(self, id_token, check_revoked: bool = False, clock_skew_seconds: int = 0): ...
    def revoke_refresh_tokens(self, uid) -> None: ...
    def get_user(self, uid): ...
    def get_user_by_email(self, email): ...
    def get_user_by_phone_number(self, phone_number): ...
    def get_users(self, identifiers): ...
    def list_users(self, page_token: Incomplete | None = None, max_results=...): ...
    def create_user(self, **kwargs): ...
    def update_user(self, uid, **kwargs): ...
    def set_custom_user_claims(self, uid, custom_claims) -> None: ...
    def delete_user(self, uid) -> None: ...
    def delete_users(self, uids): ...
    def import_users(self, users, hash_alg: Incomplete | None = None): ...
    def generate_password_reset_link(self, email, action_code_settings: Incomplete | None = None): ...
    def generate_email_verification_link(self, email, action_code_settings: Incomplete | None = None): ...
    def generate_sign_in_with_email_link(self, email, action_code_settings): ...
    def get_oidc_provider_config(self, provider_id): ...
    def create_oidc_provider_config(self, provider_id, client_id, issuer, display_name: Incomplete | None = None, enabled: Incomplete | None = None, client_secret: Incomplete | None = None, id_token_response_type: Incomplete | None = None, code_response_type: Incomplete | None = None): ...
    def update_oidc_provider_config(self, provider_id, client_id: Incomplete | None = None, issuer: Incomplete | None = None, display_name: Incomplete | None = None, enabled: Incomplete | None = None, client_secret: Incomplete | None = None, id_token_response_type: Incomplete | None = None, code_response_type: Incomplete | None = None): ...
    def delete_oidc_provider_config(self, provider_id) -> None: ...
    def list_oidc_provider_configs(self, page_token: Incomplete | None = None, max_results=...): ...
    def get_saml_provider_config(self, provider_id): ...
    def create_saml_provider_config(self, provider_id, idp_entity_id, sso_url, x509_certificates, rp_entity_id, callback_url, display_name: Incomplete | None = None, enabled: Incomplete | None = None): ...
    def update_saml_provider_config(self, provider_id, idp_entity_id: Incomplete | None = None, sso_url: Incomplete | None = None, x509_certificates: Incomplete | None = None, rp_entity_id: Incomplete | None = None, callback_url: Incomplete | None = None, display_name: Incomplete | None = None, enabled: Incomplete | None = None): ...
    def delete_saml_provider_config(self, provider_id) -> None: ...
    def list_saml_provider_configs(self, page_token: Incomplete | None = None, max_results=...): ...
