from _typeshed import Incomplete
from google.cloud import storage

def bucket(name: Incomplete | None = None, app: Incomplete | None = None) -> storage.Bucket: ...

class _StorageClient:
    STORAGE_HEADERS: Incomplete
    def __init__(self, credentials, project, default_bucket) -> None: ...
    @classmethod
    def from_app(cls, app): ...
    def bucket(self, name: Incomplete | None = None): ...
