GRANT USAGE ON SCHEMA v TO PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA v GRANT SELECT ON TABLES TO xdb_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA v GRANT SELECT, UPDATE, INSERT ON TABLES TO xdb_logger;
ALTER DEFAULT PRIVILEGES IN SCHEMA v GRANT ALL ON TABLES TO xdb_admin;


GRANT SELECT ON ALL TABLES IN SCHEMA v TO xdb_viewer;
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA v TO xdb_logger;
GRANT CREATE ON SCHEMA v TO xdb_admin;
GRANT ALL ON ALL TABLES IN SCHEMA v TO xdb_admin;