from typing import Any, Optional
from google.cloud.firestore_v1 import CollectionReference

class Client:
    def __init__(self, project: str = "", database: str = "") -> None: ...
    def collection(self, collection_path: str) -> CollectionReference: ...
    def transaction(self) -> Any: ...
