from typing import Any, Optional, Dict
from google.cloud.firestore_v1 import DocumentSnapshot, CollectionReference

class DocumentReference:
    def get(self) -> DocumentSnapshot: ...
    def set(self, data: Dict[str, Any], merge: bool = False) -> None: ...
    def update(self, data: Dict[str, Any]) -> None: ...
    def delete(self) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def parent(self) -> CollectionReference: ...
